### ISSUE TITLE
Colors are wrong when installed otherwise correctly

### ISSUE THREAD

**Issue by verbose1** [grassmunk/Chicago95#100]
Pretty self-explanatory, the colors of the OS are wrong in a few places.
https://imgur.com/mpEkj7x.png
https://imgur.com/HXLIo2L.png

What is causing this? Is there a way for me to manually change this?

**Comment by verbose1** [comment]
You can close this if it isn't relevant, but in all other examples of this theme being installed the highlight isn't magenta and the window options aren't this ugly dark grey. I can always give reinstallation a try if I can't edit it myself

**Comment by grassmunk** [comment]
So we'll need a bit more information to troubleshoot exactly what is going one. What version of XFCE/Xubuntu are you using? What version of GTK are you using? I saw you installed the theme system wide, does it have the same problems if you install the theme locally? I recently (last week) installed the theme to a new Xubuntu build and had none of the problem you noted so any information beyond the screenshots would be helpful.

**Comment by verbose1** [comment]
I'm not sure how to find xfce version, I tried xfce4-about but it came back with nothing, and if it helps I am using Manjaro. I can't use dpkg -s libgtk-3-0|grep '^Version' either because Manjaro

**Comment by verbose1** [comment]
okay i still don't know gtk version exactly but it's gtk 3 and im using xfce 4.14

**Comment by EMH-Mark-I** [comment]
Xfce 4.14 is the latest release of the desktop. This would mean GTK3.22 or newer on your desktop, which is fine. This theme support 3.22 and 3.24.

Your screen shots look very unusual though. Can check the override file in `~./config/gtk-3.0/` and cat it out here?

**Comment by verbose1** [comment]
I wouldn't know how to do that. Is the override file gtk.css, and if so how do I upload it here?

**Comment by EMH-Mark-I** [comment]
Yes, it's gtk.css. Anything applied to that file will override the theme. We have one as part of Chicago95 for some optional additional enchantments, but I was wondering if you have a file there from some other theme or for some other purpose.

You can open the file in a text editor, select all, copy & paste; or attach the file here to the GitHub issue tracker.

----

> Also to try and fix the problem I deleted the local files and now I have no theme

So when you say that you deleted the local files, these were the Chicago95 theme files located in your home directory at `/home/$USER/.themes` correct?

**Comment by verbose1** [comment]
the gtk file just imports colors.css, and colors css is as follows:
@define-color theme_fg_color #d3dae3;
@define-color theme_bg_color #181b28;
@define-color theme_text_color #d3dae3;
@define-color theme_base_color #161925;
@define-color theme_view_hover_decoration_color #c50ed2;
@define-color theme_hovering_selected_bg_color #c50ed2;
@define-color theme_selected_bg_color #c50ed2;
@define-color theme_selected_fg_color #fefefe;
@define-color theme_view_active_decoration_color #c50ed2;
@define-color theme_button_background_normal #1e2233;
@define-color theme_button_decoration_hover #c50ed2;
@define-color theme_button_decoration_focus #c50ed2;
@define-color theme_button_foreground_normal #c3c7d1;
@define-color theme_button_foreground_active #fefefe;
@define-color borders #474b57;
@define-color warning_color #ff6a00;
@define-color success_color #71f79f;
@define-color error_color #ed254e;
@define-color theme_unfocused_fg_color #d3dae3;
@define-color theme_unfocused_text_color #d3dae3;
@define-color theme_unfocused_bg_color #181b28;
@define-color theme_unfocused_base_color #161925;
@define-color theme_unfocused_selected_bg_color_alt #510a5a;
@define-color theme_unfocused_selected_bg_color #510a5a;
@define-color theme_unfocused_selected_fg_color #d3dae3;
@define-color theme_button_background_backdrop #1e2233;
@define-color theme_button_decoration_hover_backdrop #c50ed2;
@define-color theme_button_decoration_focus_backdrop #c50ed2;
@define-color theme_button_foreground_backdrop #c3c7d1;
@define-color theme_button_foreground_active_backdrop #d3dae3;
@define-color unfocused_borders #474b57;
@define-color warning_color_backdrop #ff6a00;
@define-color success_color_backdrop #71f79f;
@define-color error_color_backdrop #ed254e;
@define-color insensitive_fg_color #555964;
@define-color insensitive_base_fg_color #545863;
@define-color insensitive_bg_color #161926;
@define-color insensitive_base_color #151723;
@define-color insensitive_selected_bg_color #161926;
@define-color insensitive_selected_fg_color #555964;
@define-color theme_button_background_insensitive #1c2030;
@define-color theme_button_decoration_hover_insensitive #541966;
@define-color theme_button_decoration_focus_insensitive #541966;
@define-color theme_button_foreground_insensitive #535765;
@define-color theme_button_foreground_active_insensitive #555964;
@define-color insensitive_borders #262935;
@define-color warning_color_insensitive #633317;
@define-color success_color_insensitive #33624c;
@define-color error_color_insensitive #5d1b31;
@define-color insensitive_unfocused_fg_color #555964;
@define-color theme_unfocused_view_text_color #545863;
@define-color insensitive_unfocused_bg_color #161926;
@define-color theme_unfocused_view_bg_color #151723;
@define-color insensitive_unfocused_selected_bg_color #161926;
@define-color insensitive_unfocused_selected_fg_color #555964;
@define-color theme_button_background_backdrop_insensitive #1c2030;
@define-color theme_button_decoration_hover_backdrop_insensitive #541966;
@define-color theme_button_decoration_focus_backdrop_insensitive #541966;
@define-color theme_button_foreground_backdrop_insensitive #535765;
@define-color theme_button_foreground_active_backdrop_insensitive #555964;
@define-color unfocused_insensitive_borders #262935;
@define-color warning_color_insensitive_backdrop #633317;
@define-color success_color_insensitive_backdrop #33624c;
@define-color error_color_insensitive_backdrop #5d1b31;
@define-color link_color #5294e2;
@define-color link_visited_color #7cb7ff;
@define-color tooltip_text #d3dae3;
@define-color tooltip_background #353945;
@define-color tooltip_border #5c616c;
@define-color content_view_bg #161925;
@define-color theme_titlebar_background rgb(47,52,63);
@define-color theme_titlebar_foreground rgb(211,218,227);
@define-color theme_titlebar_background_light #181b28;
@define-color theme_titlebar_foreground_backdrop rgb(102,106,115);
@define-color theme_titlebar_background_backdrop rgb(47,52,63);
@define-color theme_titlebar_foreground_insensitive rgb(102,106,115);
@define-color theme_titlebar_foreground_insensitive_backdrop rgb(102,106,115);

and yes i deleted local files from .themes and .icons which made everything disappear so i put them back. From the looks of it, my weird colors probably has something to do with the colors.css file

**Comment by EMH-Mark-I** [comment]
OK so all of that is going to cause an issue for any GTK theme you attempt to use.

I see from your other ticket #99 that you were attempting to install the theme on a KDE Plasma desktop. I'm not familiar with KDE or Manjaro enough, but I'm going to guess that those files are auto generated from a theme editor application; likely to make GTK desktop applications blend a little better with QT desktop applications.

You can rename the gtk.css file to gtk.css_bak to keep a backup of it. That should keep your desktop from loading it so long it isn't named "gtk.css." Otherwise your desktop will pick it up and load your colour settings. (Note: I don't know if loading back into KDE is going to immediately regenerate that file. Might keep that in mind if you ever switch around desktop environments.)

Anyhow, with that file renamed or moved elsewhere, reload the theme again from the XFCE desktop and see if that helps.

**Comment by verbose1** [comment]
I am glad to say that your suggestion did the trick! Everything looks perfect now! Thanks so much for your help.

**Comment by EMH-Mark-I** [comment]
No problem, you're welcome!
