### ISSUE TITLE
Background Turns to Grey, No other settings can be applied

### ISSUE THREAD

**Issue by Simpleton95** [grassmunk/Chicago95#102]
I'm using Ubuntu MATE 18.04.1, and everything from this theme works as it should, except for the desktop background. It defaults to a grey color, and no matter what settings I choose (no background, solid background, images), it stays grey. When logging out or in, the default Win95 background flashes on the screen for a second then disappears. Which is understandable when logging out, because my login manager will take over, but when logging in, it flashes for just a second then defaults to grey. Is there a certain file that hard-codes the background? Would that be in the gtk.css or some other file?

**Comment by EMH-Mark-I** [comment]
I'll take a look at this. I re-call seeing it before. I believe this is being caused by the Caja file manager, which is used for displaying desktop icons.

It's late where I'm at so I'll have a look tomorrow.

**Comment by Simpleton95** [comment]
I see, thanks for the response. 
I'll try some different things with some of the files in the meantime, and if I find the solution, I'll make sure to post it back here. Hopefully you'll find the solution before I do, since you've seen this issue before. Thanks again.

**Comment by EMH-Mark-I** [comment]
OK I've found the cause. I'll be submitting it soon as well as some other tweaks for the MATE desktop (Brisk menu and MATE control panel.)

**Comment by Simpleton95** [comment]
Thanks! I'll be glad to actually see something besides #c0c0c0 as my desktop, hahaha. 
Overall it seems to work fine as it is, but hopefully these extra tweaks will make it a little more faithful to the original.

**Comment by EMH-Mark-I** [comment]
I've applied the changes. Try it out now.

**Comment by GDGooD** [comment]
This seems to be fixed, tested in MATE 1.22.2.

**Comment by EMH-Mark-I** [comment]
Great!
