### ISSUE TITLE
GTK3 issues from merged pull request #9

### ISSUE THREAD

**Issue by EMH-Mark-I** [grassmunk/Chicago95#11]
https://github.com/grassmunk/Chicago95/pull/9/files

In the overview you will see there were many removals of code. This is causing a lot of issues for GTK3 applications now in which context menus are missing borders, missing mouse hover highlights, and other minor flaws that are degrading usability of the theme. There are widget icons missing now and the gtk-widgets-assets.css file is also completely gone.

Is it possible to restore back and then re-implement the additions / changes while retaining original code?

Though my knowledge in github is limited, I'm going to see if I can't fix this in the mean time.

**Comment by AdrianoML** [comment]
Are you using old gnome/gtk3? These new changes were made for gtk 3.20/3.22, any version older than that will be incompatible with these changes. Unfortunately you need to keep using the old version if you are stuck with grk 3.18

**Comment by EMH-Mark-I** [comment]
Oh yeah I forget to reply to this. Just to put it on the record I was using an older version of GTK. I maintain a version of the theme for Ubuntu 16.04 now for anyone like myself that strictly runs LTS releases.
