### ISSUE TITLE
White frame in desktop overlaps background

### ISSUE THREAD

**Issue by Naveed44** [grassmunk/Chicago95#112]
Similar to #102, that piece of code fixes almost the problem (if i enable it my wallpaper change to #c0c0c0, so its working) but that white frame overlaps it.
![ss](https://user-images.githubusercontent.com/48658238/79197277-0e633c00-7df7-11ea-9408-36368479dc2a.png)

I'm using Ubuntu 18.04, Openbox, not fully DE integration, just the WM, idk what frame of nautilus-desktop is, so it's hardcoded on gtk-widgets?
Other themes works well with my feh-bg.
Hope to find the solution, if i find it i'll post it here.

**Comment by Naveed44** [comment]
I realize it's from gtk-scrolledwindow

![ss](https://user-images.githubusercontent.com/48658238/79203656-f55f8880-7e00-11ea-9c05-f83c14795fed.png)

If i disable it my wallpaper is showed, but now the file manager looks transparent too. A soul for a soul (xd)
I think i'm gonna close the issue, but if a better solution comes please let me know

**Comment by EMH-Mark-I** [comment]
I'll take a look at this. I've been cleaning up the theme and reorganizing it to prevent these type of issues, but haven't yet merged those from staging into the master branch.

**Comment by EMH-Mark-I** [comment]
OK, I've updated the theme. This will remove the white background from the desktop, but also retain it in the file manager.

I've also included some additional colouring options in the gtk.css colour map file (See line 104 in Chicago95/gtk-3.0/gtk.css)

**Comment by Naveed44** [comment]
Yep, it works as you said, Thank you, and also thanks for that icon-text color, I hadn't even realized they were wrong (black). Greetings.
