### ISSUE TITLE
Hand cursors don't work

### ISSUE THREAD

**Issue by chunga2020** [grassmunk/Chicago95#119]
Ubuntu 20.04, XFCE 4.14. Some cursors like the arrow and the resize cursors appear as expected. But the hand cursors default to their Ubuntu appearance, regardless of which color I pick.

Here's my directory listings. All top-level directories reside in `~/.icons`:

[dirs.txt](https://github.com/grassmunk/Chicago95/files/4529879/dirs.txt)

**Comment by EMH-Mark-I** [comment]
I'll take a look at this.

**Comment by chunga2020** [comment]
> I'll take a look at this.

Thanks. If you need any more information, just let me know.

**Comment by EMH-Mark-I** [comment]
OK, so right now the hand pointer is working for me on an XUbuntu 20.04 VM.

Have you rebooted your system already? Sometimes the cursor theme won't completely apply across applications until you reboot; however I've seen this occur before.

It might be necessary to delete the cursor theme from `~/.icons/` and copy it over to `/usr/share/icons` .

Have you observed this from any other cursor theme?

**Comment by chunga2020** [comment]
I just tried rebooting my system, to no avail. I also moved the cursor themes to `/usr/share/icons`, and they still don't work. I notice this issue with "handhelds", "redglass", and "whiteglass" as well. Does that therefore make it a system issue and not a theme issue? The hand pointers do, however, work for the DMZ and Yaru themes.

**Comment by chunga2020** [comment]
I think it might be a Chromium-specific issue. I searched for "cursor test page" and found [this test page](http://elektronotdienst-nuernberg.de/bugs/cursor.html). Opening this page in Chromium and testing it causes the behavior I've been seeing, but opening it in, say, Firefox, for whatever reason, fixes the problem.

**Comment by EMH-Mark-I** [comment]
That's a neat a site, thanks!
