### ISSUE TITLE
Is this compatible with Xubuntu 20.04 yet? See some issues in the next comment.

### ISSUE THREAD

**Issue by lan-vuhoang** [grassmunk/Chicago95#121]
Is this compatible with Xubuntu 20.04 yet? I asked because I think this is the closest to Windows 95 that Linux could be, and I just remade my Xubuntu VM from stretch because of Xubuntu 20.04 and UEFI.

**Comment by EMH-Mark-I** [comment]
Yes, the theme will work with Xubuntu 20.04.

We are also about to submit a new release (should be by the end of the month at most) which will address some issues and improve the overall fidelity and usability of the theme. If you want to see the latest work, then checkout the [staging branch.](https://github.com/grassmunk/Chicago95/tree/staging).

**Comment by lan-vuhoang** [comment]
1. The MS Sans Serif title bar font spacing is too close.
2. How do I change the font in the Start button?

**Comment by EMH-Mark-I** [comment]
1: I've seen this too. I'm not sure what to say yet about the font kerning. The instructions for setting that up might have to be adjusted in the future, or until I can contact [farmerbb](https://github.com/farmerbb) for some input. I'm not familiar enough with fonts to proficiently resolve.

2: You can change the Start Button from within the theme. For Systems using XFCE 4.14, checkout the location you've installed the theme, `--/Chicago95/gtk3.24/apps/whiskermenu.css`

You can adjust the font and weight at line 42. The primary selected font is for MS Sans Serif Bold if it's available, else it falls back to Sans or Sans-Serif.

3: For the Start Button images, are you talking about the small image files in `--/Chicago95/misc/` or the images in `--/Chicago95/misc/Legacy GTK3 start buttons`? Just trying to clarify. The images in `misc/` would be the correct images to use.

There are a variety of three images, each with three optional sizes. Whisker Menu and the Application Menu plugins handle the background image sizes differently, so you'll have to experiment a little. As an example, if you want the Windows logo for the Start Button, then change the icon settings from the Application/Whisker Menu properties window, navigate to the location you've installed the theme `--/Chicago95/misc/` and select the `windows.png` file. If the image sizing appears incorrect, then go through it again and select `windows_16x16px.png`, and if that appears incorrect then try `windows_32x32px.png`.

Also make sure that for the Start Button title, that you have it as "Start" for the label in the Whisker/Application Menu properties. Add or remove spaces where necessary.

4: You shouldn't have to completely remake the VM to install a GTK theme.

**Comment by lan-vuhoang** [comment]
3. The images are in this folder: --/Chicago95/misc/Legacy GTK3 start buttons.
4. I am going to reinstall Xubuntu, but VirtualBox's implementation of UEFI always priortize HDD boot over bootable disks.

**Comment by EMH-Mark-I** [comment]
Use the images that are directly in `--/Chicago95/misc/` and not from any of the sub-directories from therein. Those images in the sub-directories are for older versions of XFCE and its panel plugins during the time XFCE was migrating to GTK3.

**Comment by lan-vuhoang** [comment]
Also the MS Sans Serif font is too smooth, which broke the start button.

**Comment by grassmunk** [comment]
Could you share a screenshot? I tested this on a VM and a laptop and it worked fine in 20.04. 

Have you disabled font anti aliasing?

**Comment by lan-vuhoang** [comment]
Also, make a Windows 98/2000/ME variant of this theme. There's some slight differences between 95 and 98/2000/ME Classic themes.

**Comment by grassmunk** [comment]
If you would like a 98 theme I would suggest checking out Redmond97. The main differences are really colors and the gradients in the title bar. We may consider adding a Windows 98 variant at a later date. Thank you.

**Comment by lan-vuhoang** [comment]
When will the new theme be out? I am hyped for the W98/2000/ME variant/wallpapers and the redone icon set and cursors, because I saw your issues on that. I am also hyped about the redone theme if there is one, and the finished sound theme, because I saw it on the staging branch.

**Comment by EMH-Mark-I** [comment]
I would like to say within the month, but then I was saying that a month ago so I'm not really sure.

**Comment by lan-vuhoang** [comment]
> I would like to say within the month, but then I was saying that a month ago so I'm not really sure.

Why? And also I'm hyped about the other things like the wallpapers, new theme variants and redone stuff.

**Comment by EMH-Mark-I** [comment]
We're working on a few utilities that help install the theme from a graphical application, a theme changer application compatible with old Plus! .theme files, adjusting the icon theme to support symbolic icons and cleanup dead links, consolidating redundant code and images, and testing it across a few other desktop environments.

Most of that is nearly complete. Then afterwards I've been looking into adding the theme to an OBS repository, install-able for Debian based distributions and possibly a few others.

It started with just a few things here and there, but has grown into a lot more. For the most part, the GTK portion is completed.

**Comment by lan-vuhoang** [comment]
And the new release is out. Time to swept my old Xubuntu 20.04 VM and do a complete reinstall on a new one.

**Comment by lan-vuhoang** [comment]
Final results:

![image](https://user-images.githubusercontent.com/63572082/86136620-839cfe00-bb16-11ea-9698-40294d693ac7.png)

Windows 95. Link to original revamped wallpaper: [https://www.neowin.net/forum/topic/1148048-windows-95-widescreen-wallpaper/](url).

![image](https://user-images.githubusercontent.com/63572082/86137181-2c4b5d80-bb17-11ea-90f5-f2d462e69c5a.png)

Windows 98, the version that leads to the boom of the internet. Link to remastered wallpaper: [https://www.deviantart.com/archi-techi/art/Windows-98-Remastered-Startup-Screen-4K-Wallpaper-645517359](url). Just need a start menu banner, a new terminal starting message and a gradient in the title bar.

![image](https://user-images.githubusercontent.com/63572082/86137971-0a060f80-bb18-11ea-949e-ff21689a1d5b.png)

Windows ME. The last version with the obsolete 9x DOS kernel before it's replaced with the superior NT kernel in Windows XP. Wallpaper: [https://www.deviantart.com/master-bit/art/Windows-ME-Wallpaper-4K-Remastered-732283046](url). Just need a start menu banner, a new terminal start message and a gradient in the title bar.

![image](https://user-images.githubusercontent.com/63572082/86138853-30787a80-bb19-11ea-9b3a-3efd7c4cf79e.png)

And finally, Windows 2000! The first version of Windows to have the NT kernel without the NT string in the name and all the new desktop features that's going to be introduced to the home users in Windows XP. Wallpaper: https://www.deviantart.com/master-bit/art/Windows-2000-Wallpaper-4K-Remastered-732122164

**Comment by lan-vuhoang** [comment]
Also, Redmond97 is a bit gimmicky. So I want a Windows 98 variant, maybe even in a seperate package like Memphis98 or something. Also, include the Windows 2000/ME stuff in there or something.
