### ISSUE TITLE
This theme is awesome! I want more themes.

### ISSUE THREAD

**Issue by lan-vuhoang** [grassmunk/Chicago95#122]
The Chicago95 theme is awesome. I has used it on my Xubuntu 20.04 VM. So is there any more themes? Maybe WhistlerXP for XP, a Vista theme (I don't know a suitable name for that, maybe Longhorn6.0?), Windows 7 theme (don't know a suitable name for that either) or a macOS style theme? I can't wait.

**Comment by EMH-Mark-I** [comment]
Thanks!

There might be other themes out there that emulate the Windows 7 / Vista aero appearance, and I'm sure there are some Windows XP themes out there too. You will have to look around though because I don't know any of them by name.

I've seen numerous MacOS themes around before as well.

**Comment by grassmunk** [comment]
If you want more themes check out: https://archive.org/details/windowsdesktopthemes?&sort=-publicdate and use them with ChicagoPlus in the plus folder.

**Comment by lan-vuhoang** [comment]
Yeah, but the other Windows themes that I saw are outdated and I like the little "quality of life" tweaks that you have in Chicago95.

**Comment by grassmunk** [comment]
Check out the staging version and look at the new Plus tool to convert those themes to this theme. Its easy.

**Comment by lan-vuhoang** [comment]
I mean the Windows XP/Vista/7 themes.

**Comment by lan-vuhoang** [comment]
I want Windows XP/Vista/7 themes as the themes that I found was outdated except for the b00merang theme, but they aren't as polished as some of the older themes do.

Also, are you even listening?

**Comment by grassmunk** [comment]
This is a Windows 95 re-imagining on linux. If you want XP/Vista/7 themes check out gnome-look.org
