### ISSUE TITLE
XP/Vista/7 themes, please.

### ISSUE THREAD

**Issue by lan-vuhoang** [grassmunk/Chicago95#128]
I've already made an issue on that, but it's been closed and made off topic by grassmunk so I can no longer post on it. So I made this issue as a continuation of that issue.

The issue was asking for Windows XP/Vista/7 themes. grassmunk asked me to check on gnome-look.org but it's filled with old themes and unrelated themes. The b00merang themes are decent, but they lacks some of the polishing that some of the older themes has, at least from the screenshots that I saw. 

I also really like the "quality of life" tweaks that Chicago95 has, so I want them in the new XP/Vista/7 themes too.

**Comment by EMH-Mark-I** [comment]
Chicago95 is a hobby project, we only have so much available time to designate it outside of work and family. (Mostly a two person ran project.)

It's difficult enough just making a classic Windows 95/98 era GTK and Icon theme for a skeuomorphic hostile toolkit.

A Windows XP/Vista/7 theme is not going to happen here; I'm sorry.

**Comment by lan-vuhoang** [comment]
Just keep trying.

Also, hint: For a Windows 7 theme, DockBarX could be used to replicate the Windows 7 Superbar. You may need to make your own theme for it, though. Official repo: [https://github.com/M7S/dockbarx](url)

Install steps: (from the official repo)

`sudo add-apt-repository ppa:xuzhen666/dockbarx`
`sudo apt-get update`
`sudo apt-get install dockbarx`

Use DockBarX as an XFCE applet:

`sudo apt-get install xfce4-dockbarx-plugin`

More themes:

`sudo apt-get install dockbarx-themes-extra`
