### ISSUE TITLE
Add win95 sounds

### ISSUE THREAD

**Issue by phil294** [grassmunk/Chicago95#13]
Seems pretty obvious, doesn't it? :) 
This repository is awesome, imo the soundbank would make it complete.

**Comment by jacobpoo** [comment]
@phil294 How do you expect to make sounds with XFCE?

**Comment by phil294** [comment]
@jacobpoo @grassmunk I dont know, I am not the creator of this repository.
There are numerous ways to have a melody played on startup or shutdown. notify-send, error alerts, update notifications etc. binaries could all be replaced with "play respective sound and then do the original alert"-scripts.
I don't really see your point. And in case you'll want to say "you can do that yourself": as far as I can see, this repository is both a theme and an overall instruction guide on how to achieve a win95-alike look and feel. These steps would fit in here very well.

**Comment by phil294** [comment]
Ok, so I am not really sure why this got closed, but for any curious future readers, the most compact and correct steps for getting to run system sounds in xfce can be found [here](https://www.dropbox.com/s/f65axtt6vclx3xo/Smooth.tar.gz?file_subpath=%2FSmooth%2Fdocumentation%2Fhow+to+install+on+xfce.txt) (in this case, for the "Smooth" sound theme).

For the sake of archiving, I will copy it here:
<details>
  <summary>Click to expand</summary>

```
Adapted from https://ubuntuforums.org/showthread.php?t=2263834&amp;s=21da51e852349f734144425885d56ac9&amp;p=13221570#post13221570
Thank you very much to the author "Toz"

1. Install some required packages:
sudo apt-get install gnome-session-canberra sox

2. Download the sound theme

3. Extract the file:
tar xzvf Smooth.tar.gz

4. Copy the extracted content ("Smooth" folder) to your sounds directory:
 /.local/share/sounds
(create the "sounds" directory if it does not exist yet)

5. Enable sound events and feedback sounds.

In example in Mate go to Control Center --&gt; Sounds and enable them there; in Xfce it is done by entering in the terminal:
xfconf-query -c xsettings -p /Net/EnableEventSounds -s true
xfconf-query -c xsettings -p /Net/EnableInputFeedbackSounds -s true


6. Set "Smooth" as the default sound theme

In example in Mate go to Control Center --&gt; Sounds and set it there; in Xfce it is done by entering in the terminal:
xfconf-query -c xsettings -p /Net/SoundThemeName -s "Smooth"

7. Setup the necessary environment variable. Add to the end of ~/.profile:
Code:

GTK_MODULES="$GTK_MODULES:canberra-gtk-module"
export GTK_MODULES

That should be it. Perhaps a logout is needed before it starts working.

--//--

8. For a startup sound, create a new autostart application (Settings Manager or Control Center &gt;&gt; Session and startup &gt;&gt; Application autostart) with the following parameters:
- Name = Login Sound
- Command = canberra-gtk-play -f ~/.local/share/sounds/Smooth/stereo/desktop-login.oga

9. For logout sound, you need override xfce4-session. To do so, with root privliges, create the file /usr/local/bin/xfce4-session with the following content:

#!/bin/bash

# run the real xfce4-session executable
/usr/bin/xfce4-session

# on exit, run my stuff
canberra-gtk-play -f ~/.local/share/sounds/Smooth/stereo/desktop-logout.oga

...and make this file executable:
sudo chmod +x /usr/local/bin/xfce4-session
```
</details>
