### ISSUE TITLE
How do i revert bash to normal

### ISSUE THREAD

**Issue by KamenkoTV** [grassmunk/Chicago95#130]
i have tested your theme and it's good but now i want my terminal back to normal
i'm on OpenSUSE Linux.

![image](https://user-images.githubusercontent.com/48242163/85962416-dfe60d80-b9b0-11ea-9ac9-d40cc266c5d5.png)

**Comment by EMH-Mark-I** [comment]
1: Open your file manager and enable hidden files (Can usually reveal hidden files with `Ctrl-h`.)
2: Locate .bashrc in your home directory (/home/$USER/.bashrc) and open it with a text editor.
3: Scroll to the bottom of the file and delete *only* the following:

    # Emulate an MS-DOS prompt in your Linux shell.
    # Laszlo Szathmary (jabba.laci@gmail.com), 2011
    # Project home page:
    # https://ubuntuincident.wordpress.com/2011/02/08/emulate-the-ms-dos-prompt/
    #
    #
    # Modified by Soldier of Fortran
    #
    # Add to you ~/.bashrc file with: 'source ~/.themes/95/bashrc'
    
    function msdos_pwd
    {
        local dir="`pwd`"
    
        echo $dir | tr '/' '\\'
    }

    export PS1='C:`msdos_pwd`> '
    
    echo 
    echo
    echo "Microsoft(R) Windows 95"
    echo "   (C)Copyright Microsoft Corp 1981-1996."
    echo

**Comment by KamenkoTV** [comment]
Thanks it worked.
