### ISSUE TITLE
where's windows98 folder

### ISSUE THREAD

**Issue by appleyuchi** [grassmunk/Chicago95#139]
where's windows98 folder?
I can not find it

and ...................................
could you tell me how to  change the background of folder to black,
it'll be better for our eyes to relax~

Thanks for your help~!

**Comment by grassmunk** [comment]
it's in `C:\Windows\`

What do you mean change the folder background to black? 

If you mean change the theme colors run `PlusGui.py` from the `Plus/` folder and check themes from  https://archive.org/details/windowsdesktopthemes?sort=-publicdate

Like:
https://archive.org/details/themes_divano_202005
or
https://archive.org/details/themes_karr_202005
