### ISSUE TITLE
Please enable login startup sound

### ISSUE THREAD

**Issue by tuxkernel** [grassmunk/Chicago95#14]
Enable login startup sound:

Go to System > Preferences > Startup Applications. "Add"

Create a new startup program:

Name: Startup Sound
Command: paplay /YOUR/PATH/FILE/SOUND

Example: paplay /home/tuxkernel/MATE/Windows95/Sounds/STARTUP.wav

Comment: Startup Sound.

Done.

[Startup_Sound.tar.gz](https://github.com/grassmunk/Chicago95/files/1171238/Startup_Sound.tar.gz)

**Comment by bmintz** [comment]
On my system, it takes about ten seconds after login for it to play. :(

**Comment by EMH-Mark-I** [comment]
I added the startup sound in the Extras/ directory along with instructions in the INSTALL.md, Optional configurations sections, Windows 95 login startup sound. Pretty cool!
