### ISSUE TITLE
Desktop Icons have weird checkered pattern on them

### ISSUE THREAD

**Issue by Lalarian** [grassmunk/Chicago95#145]
Hello!
I really love the Chicago95 idea, and I haven't been using as comfortable in using a desktop for years, since I left Windows XP behind! (Flat design is a burden to humanity and every sane mind!)

So I have installed Chicago 95 in my XFCE 4.14 desktop running in Manjaro and I also used Chicago95Plus for installing a stock Windows 200 theme.
You can see a partial screenshot here:
![chicago95](https://user-images.githubusercontent.com/5146616/91001640-8e32bb80-e5cc-11ea-8ce3-993f861f69cd.png)

As you can se best at the trashcan icon, there's pattern on the icon, similar to a checkerboard.
It has been there with the original Chicago95 theme aswell as with the Windows 2000 theme.
It's rather unpleasant to the eye in original size. What could be the reason?
Thank you! :)

**Comment by grassmunk** [comment]
This is due to the way that Chicao95 upscales 32x32 icons using Inkscape. You can try messing with the chicago95plus command line options to try and increase the number of colors/overlap to eliminate this banding.

**Comment by Lalarian** [comment]
Hello!

thank you very much!
It is working fine with icon size set to 48 with the stock W2K icons!
