### ISSUE TITLE
Window borders missing on the sides when maximized.

### ISSUE THREAD

**Issue by belad0** [grassmunk/Chicago95#147]
I noticed the window borders missing on the sides when a window such as the File Manager is maximized. Is this intentional? I saw this on the screenshots posted here too. 
It looks a bit inconsistent, especially at the level of the title bar, since the top border is visible. 

(The bottom border appears to be missing in maximized windows as well, this is less of a problem visually but it might become more evident if the side borders are displayed...)

**Comment by EMH-Mark-I** [comment]
The borders (left, right, top, and bottom) should be completely disabled when the application is maximized. For awhile this wasn't the case due to the window manager theme, but it should be now.

This was resolved after PR #142, however to see the changes made you'll have to manually download and install the theme since it hasn't been applied to a release. I'm also unsure if it's applied to the Debian packaged version either since it's based on the releases from here.

**Comment by belad0** [comment]
I copied the cloned Theme/Chicago95 directory to /usr/share/themes/ but the top border is still visible? Is the fix somewhere else? Or is my Debian buster (no backports) incompatible with the fix?

**Comment by EMH-Mark-I** [comment]
OK I'll have to take a look at it. I thought it was fixed, but perhaps not? I don't see a difference on mine either.

**Comment by huyhoang8398** [comment]
Go to `settings editor` -> `xfwm4` untick `borderless_maximize`

**Comment by EMH-Mark-I** [comment]
You would most definitely want to keep the borderless_maximize option enabled. Disabling it would cause all borders to be rendered for maximized applications.

After looking into the issue I've found that the this has been correctly addressed as seen from PR #142. The change in that PR sets a property `frame_border_top` with a value of 4 (this will crop the top border by 4 pixels.) From further investigation the `frame_border_top` property is a [recent addition for XFWM 4.14](https://github.com/xfce-mirror/xfwm4/commit/bf41e461abe520d20cf2022e697cd38bc28867e8#diff-30b1e0a62e4541bbd81e74899c49c30065cc0982d334d7a35d187bd7937f2eec). It is not present for previous versions of XFWM. This will mean that older versions of the window manager will be unable to take advantage of this feature.

If you want to resolve the top border effect, then I recommend upgrading your window manager (or to a version of your operating system that has packaged the newer version of XFWM4.)
