### ISSUE TITLE
Libreoffice Icons Bar displaying incorrectly using Chicago 95 and XFCE

### ISSUE THREAD

**Issue by BalooRJ1** [grassmunk/Chicago95#148]
https://imgur.com/CMpKr1t.png

In Libreoffice, icons are disappearing and menus are not displaying properly while using XFCE and Chicago95. This is using Pop! OS 20.10, but the same issue existed in 20.04 as well. This issue does not appear on the same system where Pop's GNOME Desktop environment is installed, on that DE LibreOffice displays properly.

**Comment by EMH-Mark-I** [comment]
I'll take a look at it. The new version of LibreOffice appears to place each combobox entry on the toolbar inside of a viewport, within a grid, within a scrolledwindow. I'm unsure of why or to what purpose it would serve, but I should be able to address it.

**Comment by EMH-Mark-I** [comment]
Try it out now. You'll have to re-download or update your local repository of the theme as well as re-install the theme to see the latest changes made.

**Comment by BalooRJ1** [comment]
Now I am getting this when I run python3 on the installer.py:

File "/home/baloo/Downloads/Chicago95-master/installer.py", line 598, in <module>
    app = InstallGUI()
  File "/home/baloo/Downloads/Chicago95-master/installer.py", line 26, in __init__
    self.set_style()
  File "/home/baloo/Downloads/Chicago95-master/installer.py", line 45, in set_style
    provider.load_from_path(running_folder + "/Theme/Chicago95/gtk-3.24/gtk.css")
gi.repository.GLib.Error: gtk-css-provider-error-quark: whiskermenu.css:65:13Expected a length (1)

**Comment by EMH-Mark-I** [comment]
Issue resolved after previous commit fixed syntax mistake in the whiskermenu.css file.
