### ISSUE TITLE
Please enable GRUB Image background

### ISSUE THREAD

**Issue by tuxkernel** [grassmunk/Chicago95#15]
Open a terminal and type:

$ sudo apt-get install grub2-splashimages
$ sudo cp /usr/share/images/desktop-base/desktop-grub.png /home/YOURUSERNAME/ # Default GRUB image backup

Then copy the new desktop-grub.png image in /usr/share/images/desktop-base/

$ sudo update-grub
$ sudo update-grub2
$ sudo reboot

Done.

[Grub-Images-Backgrounds.tar.gz](https://github.com/grassmunk/Chicago95/files/1171255/Grub-Images-Backgrounds.tar.gz)

**Comment by jacobpoo** [comment]
That could be quite cool @grassmunk
		
	





On Mon, Jul 24, 2017 at 5:22 PM -0400, "noel_merino@yahoo.com.mx" <notifications@github.com> wrote:












Open a terminal and type:


$ sudo apt-get install grub2-splashimages

$ sudo cp /usr/share/images/desktop-base/desktop-grub.png /home/YOURUSERNAME/ # Default GRUB image backup


Then copy the new desktop-grub.png image in /usr/share/images/desktop-base/


$ sudo update-grub

$ sudo update-grub2

$ sudo reboot


Done.


Grub-Images-Backgrounds.tar.gz

**Comment by grassmunk** [comment]
Hi, 

As a mentioned in your other post, please add all your updates to a pull request in the 'Extras' folders and updated the Readme, I'll approve the pull request.
