### ISSUE TITLE
go-previous Icon misaligned

### ISSUE THREAD

**Issue by spmfox** [grassmunk/Chicago95#152]
The go-previous.svg, and all scaled down PNG versions of this icon are misaligned. Looking at the other icons, it appears that go-previous needs to start at Y:16 and right now it starts at Y:8.

I was able to edit this file using inkscape, and it looks good, however when I tried scaling it down via different methods to place into the 16/22/24/34/48 folders I was having difficulties getting the export settings correct for the PNGs. No matter what I did they came out blurry.

I want to help but I also don't want to edit something and dilute it's quality, so I figured I would open this issue instead. See the attached screenshots to show the misalignment.

![misaligned-1](https://user-images.githubusercontent.com/2227281/101513064-bced5b80-3949-11eb-9a57-ba5c1f5c80be.png)
![misaligned-2](https://user-images.githubusercontent.com/2227281/101513067-bd85f200-3949-11eb-871f-e786ee0dbf81.png)

**Comment by grassmunk** [comment]
Just pushed a fix to these, let me know if it works and i'll close the issue

**Comment by spmfox** [comment]
@grassmunk yes it works, cloned the repo and told the installer to only update the icons - everything worked perfect and the icon is indeed updated.

Thank you!
