### ISSUE TITLE
Failed to import: Error opening file ./Theme/Chicago95/gtk-3.24/gtk.css: Not a directory (2)

### ISSUE THREAD

**Issue by lambdagit101** [grassmunk/Chicago95#157]
I saw that when I try to open the installer for Chicago95, it kept giving me this error:
```
Traceback (most recent call last):
  File "/home/lambda/Downloads/Chicago95-2.0.1/installer.py", line 598, in <module>
    app = InstallGUI()
  File "/home/lambda/Downloads/Chicago95-2.0.1/installer.py", line 26, in __init__
    self.set_style()
  File "/home/lambda/Downloads/Chicago95-2.0.1/installer.py", line 45, in set_style
    provider.load_from_path(running_folder + "/Theme/Chicago95/gtk-3.24/gtk.css")
gi.repository.GLib.Error: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /home/lambda/Downloads/Chicago95-2.0.1/Theme/Chicago95/gtk-3.24/gtk.css: Not a directory (2)
```
gtk-3.24 is just a file with the text `gtk-3.0/` in it. This happened when using the version from the Releases section and downloading the master branch directly.
Copying the folder gtk-3.0 and renaming it as gtk-3.24 just made stuff break like my taskbar disappearing, or icons missing

**Comment by grassmunk** [comment]
I've changed the reference at that line to point to the `gtk-3.0` folder instead of the link.
