### ISSUE TITLE
Please enable screensaver

### ISSUE THREAD

**Issue by tuxkernel** [grassmunk/Chicago95#16]
In the folder there are two files

1.- Copy the file with *.desktop extension in /usr/share/applications/screensavers
2.- Copy the Windows95-floaters.png image in /usr/share/pixmaps

NOTE: Check that both files have the following characteristics:

Propietary: root
Acces: Only read

Group: root
Acces: Only read

Others:
Acces: Only read

Done.

[Screensaver.tar.gz](https://github.com/grassmunk/Chicago95/files/1171262/Screensaver.tar.gz)

**Comment by grassmunk** [comment]
Hi, 

I really love all the suggestions you've made. Would you mind placing them in the 'Extras' folder and updating the ReadMe accordingly. I'll approve the pull request.

**Comment by bmintz** [comment]
I'll probably do this at some point. You can assign it to me. @grassmunk

**Comment by grassmunk** [comment]
This has been open for more than a year, i'm closing it out.
