### ISSUE TITLE
OBS key FB2572B7B977DBCD expired

### ISSUE THREAD

**Issue by eMPee584** [grassmunk/Chicago95#164]
```
W: GPG error: http://download.opensuse.org/repositories/home:/bgstack15:/Chicago95/Debian_10  InRelease: The following signatures were invalid: EXP
KEYSIG FB2572B7B977DBCD home:bgstack15 OBS Project <home:bgstack15@build.opensuse.org> 
```

Workaround for now: adding a `[trusted=yes]` to the sources list, as in:
`deb [trusted=yes] http://download.opensuse.org/repositories/home:/bgstack15:/Chicago95/Debian_10/ /`

Thanks a lot for putting up the deb packages though, this allows me to finally set this up as easter egg for https://schulstick.org/ :+1: :grinning:

**Comment by EMH-Mark-I** [comment]
Welcome!

OpenSUSE rebuilds the OBS GPG keys every once in awhile, I don't know why, but it breaks the repo for everyone. There isn't much the maintainer can do about it since it's out of their control.
You'll have to re-add the key manually.

For your particular OBS repo Debian 10, you should be able to run:

    curl -fsSL https://download.opensuse.org/repositories/home:bgstack15:Chicago95/Debian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_bgstack15_Chicago95.gpg > /dev/null

**Comment by eMPee584** [comment]
Uhm thanks.. that is the same key however, and it expired two ½ weeks ago..

```
curl -fsSL https://download.opensuse.org/repositories/home:bgstack15:Chicago95/Debian_10/Release.key | gpg --show-keys
pub   rsa2048 2018-11-07 [SC] [expired: 2021-01-15]
      D65A6C38FACB650F55438BB7FB2572B7B977DBCD
uid                      home:bgstack15 OBS Project <home:bgstack15@build.opensuse.org>
```

**Comment by lysol** [comment]
And it's still expired, in case anyone is wondering.

    pub   rsa2048 2018-11-07 [SC] [expired: 2021-01-15]
          D65A 6C38 FACB 650F 5543  8BB7 FB25 72B7 B977 DBCD
    uid           [ expired] home:bgstack15 OBS Project <home:bgstack15@build.opensuse.org>

**Comment by EMH-Mark-I** [comment]
Alright, I'll let bgstack15 know. I'm seeing this as well too.
Thanks for reporting!

**Comment by EMH-Mark-I** [comment]
OK, it *should* be resolved now! Can you remove the key yet again, then re-add it?

    sudo apt-key del "D65A 6C38 FACB 650F 5543  8BB7 FB25 72B7 B977 DBCD"

Then update:

    sudo apt update
