### ISSUE TITLE
Plus not detecting icon and cursor in root directory

### ISSUE THREAD

**Issue by stevia1** [grassmunk/Chicago95#168]
Paths:
	Cursor Path: /root/.icons/Chicago95_Cursor_Black
	Theme Path: /root/.themes/Chicago95
	Icons Path: /root/.icons/Chicago95
Install (checkbox) Options:
	Cursors: True
	Icons: True
	Wallpaper: True
	Sounds: True
	Colors: True
	Fonts: True
	Screensaver: True
CRITICAL :: check_software         :: Either the Chicago95 or Chicago95_tux icon theme must be installed to /root/.icons/ to use this library
CRITICAL :: check_software         :: The Chicago95 cursor Chicago95_Cursor_Black must be installed to /root/.icons/ to use this library

I moved the tux and Chicago95 theme to my root directory  (individual files) and even moved the icon and cursor folders into the Icons folder but to no avail. Using debian.

**Comment by stevia1** [comment]
my apologies if this is poorly formatted never posted to github before

**Comment by grassmunk** [comment]
Can you please run again but with the `--debug` flag and post the logs here?
