### ISSUE TITLE
Installer doesn't work on a fresh arch install

### ISSUE THREAD

**Issue by nonetrix** [grassmunk/Chicago95#169]
I just insalled arch using the anarchy installer and the installer doesn't work only giving this output it seems it's trying to open a file that for some reason is not included?! 

Traceback (most recent call last):
  File "/home/nonetrix/Downloads/Chicago95-master/installer.py", line 598, in <module>
    app = InstallGUI()
  File "/home/nonetrix/Downloads/Chicago95-master/installer.py", line 26, in __init__
    self.set_style()
  File "/home/nonetrix/Downloads/Chicago95-master/installer.py", line 45, in set_style
    provider.load_from_path(running_folder + "/Theme/Chicago95/gtk-3.0/gtk.css")
gi.repository.GLib.Error: gtk-css-provider-error-quark: gtk.css:142:29Failed to import: Error opening file /home/nonetrix/Downloads/Chicago95-master/Theme/Chicago95/gtk-3.0/apps/xfce.css: No such file or directory (2)

**Comment by grassmunk** [comment]
When you ran the script were in in the Chicago95 root folder? I don't run arch but I just tested the script and it worked fine and I checked and that file exists.

**Comment by nonetrix** [comment]
Yes I was I check the folder for myself and I also couldn't find it but there was many other files in the directory.

**Comment by nonetrix** [comment]
Consider making a more minimal cli installer as a fallback preferability in bash since that's pretty much on every Linux system

**Comment by NarakuITA** [comment]
Hi, I'm not a big expert in the linux world. I use Windows, slowly, slowly I'm trying to learn how to use linux. I tried to automatically install the package, on Lubunto 20.04 on the VirtualBox virtual machine, in order not to do any damage.
Unfortunately the installation fails! 

This is what appears on the terminal:
`Installer running from: /home/andrea/Scaricati/Chicago95-master
[PANEL] Warning: xfce4-panel-profiles not installed, manual panel installation required. See INSTALL.md
[PANEL] Warning: xfce4-panel-profiles not installed, manual panel installation required. See INSTALL.md
Installing Chicago 95 with the following options:
 Components:
        Theme:          True
        Icons:          True
        Cursors:        True
        Background:     True
        Sounds:         True
        Fonts:          True
 Customizations:
        Thunar Graphics:        True
        Change Terminal Colors: True
        Set Bash Prompt:        True
        Set zsh promt/theme:    False
        Customize Panel:        False
Installing Chicago 95
Enabling Theme in XFCE4
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Enabling Icons in XFCE4
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Enabling Cursors in XFCE4
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Changing background
Warning: xfconf-query not installed, cannot auto-enable theme. Use your distros theme management to install Chicago95
Traceback (most recent call last):
  File "/home/andrea/Scaricati/Chicago95-master/installer.py", line 295, in install
    subprocess.check_call(args, stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] File o directory non esistente: 'xfconf-query'
`
The installation crashes when arriving at: Installing component: Background install_background 
Who can help me? thank you so much!

**Comment by grassmunk** [comment]
The current supported Linux is Xubuntu LTS 20.04. The script mentioned multiple times that the install won't work: `manual panel installation required. See INSTALL.md`

I'll update the install script to quit if xfconf-query is not installed and exit with a warning. 

Please see: https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md#-single-user-manual-install- for manual install.
