### ISSUE TITLE
Mousepad broken In Xubuntu 16.04.3 LTS, does not render correctly, no scrollbar

### ISSUE THREAD

**Issue by mknepper** [grassmunk/Chicago95#17]
You can see that the buttons and spacing are jacked up:

![broken](https://user-images.githubusercontent.com/12740958/29745676-46336c9c-8a87-11e7-9b5d-4f0daef6d2e0.png)

And the scrollbar is broken here:

![broken3](https://user-images.githubusercontent.com/12740958/29745680-5e894988-8a87-11e7-8154-936ef96885cd.png)

The menus are wonky too, unfortunately. Just an FYI!

Here's the output when running in a Terminal:

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:36:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:37:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:55:1: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:64:23: '-gtk-outline-radius' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:83:19: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:94:6: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:107:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:108:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:113:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:152:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:153:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:294:7: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:405:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:406:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:410:6: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:432:6: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:466:5: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:520:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:521:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:547:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:548:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:564:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:565:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:647:6: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:660:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:661:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:679:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:680:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:695:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:696:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:699:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:700:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:709:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:710:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:716:29: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:723:31: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:730:31: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:737:33: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:770:15: Missing name of pseudo-class

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:807:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:808:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1190:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1196:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1197:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1231:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1232:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1237:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1238:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1243:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1244:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1248:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1249:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1255:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1256:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1320:23: '-gtk-outline-radius' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1351:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1352:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1362:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1375:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1376:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1521:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1522:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1634:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1635:14: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1653:11: 'min-height' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1654:10: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1752:13: 'min-width' is not a valid property name

(mousepad:32538): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1753:14: 'min-height' is not a valid property name

**Comment by jacobpoo** [comment]
@kneuro Are you on GTK 3.22 or higher? I am not a dev, but this requires GTK 3.22.

**Comment by kneuro** [comment]
I'm an idiot, I thought the 16.04.3 LTS had Gnome 3.22. It's 3.18.2.

**Comment by EMH-Mark-I** [comment]
I also use 16.04 for my primary OS, which won't support newer GTK versions past 3.18.9. You can install newer GTK versions, but I don't recommend it on an LTS distro release.

I've kept a custom build of the theme pre GTK 3.22 patch with some additional fixes, but bare in mind it isn't perfect. I just put up a repo if you want the theme on XUbuntu 16.04, [check it out](https://github.com/EMH-Mark-I/Chicago95-Custom-XUbuntu-16.04-).
