### ISSUE TITLE
Way to remove the startup sound on other DEs?

### ISSUE THREAD

**Issue by That1M8Head** [grassmunk/Chicago95#171]
I deactivated the startup sound event from Xfce, and it no longer plays there.

However, when I switch the desktop environment back to the default GNOME desktop, it still plays.
I checked GNOME's startup applications and the event that was in Xfce was not there.

**Comment by grassmunk** [comment]
Here's the install instructions for sounds: https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md#-windows-95-sounds-

If you're still having problems i would remove the folder:

`rm -rf ~/.local/share/sounds/Chicago95`

Then remove a sound theme name:

`xfconf-query -c xsettings -p /Net/SoundThemeName -s  ""`

**Comment by CynicusRex** [comment]
> I deactivated the startup sound event from Xfce, and it no longer plays there.

How did you do this in the first place?

**Comment by That1M8Head** [comment]
> > I deactivated the startup sound event from Xfce, and it no longer plays there.
> 
> How did you do this in the first place?

I just disabled it in Xfce's settings, I don't remember what it was called, but it was in the settings

**Comment by CynicusRex** [comment]
> > > I deactivated the startup sound event from Xfce, and it no longer plays there.
> > 
> > 
> > How did you do this in the first place?
> 
> I just disabled it in Xfce's settings, I don't remember what it was called, but it was in the settings

Found it: “Session and Startup” → “Application Autostart” → “ ☐ Chicago95 startup sound”.
