### ISSUE TITLE
Is there a way to uninstall just the console modification?

### ISSUE THREAD

**Issue by Foxtrot-Uniform** [grassmunk/Chicago95#175]
Hello I just want to remove the modification that it did to my console. I want to keep theme icon etc everything except the console.

It keeps confusing people that I use WSL2 because of the C: and the backwards slashes.

Long story short how do I get vanilla XTerm/XFCE Term/QTerm  back?

**Comment by EMH-Mark-I** [comment]
Check issue #130. 
https://github.com/grassmunk/Chicago95/issues/130

The instructions I posted there should also apply here.
