### ISSUE TITLE
Unpleasant Terminal dropdown menu

### ISSUE THREAD

**Issue by bropear** [grassmunk/Chicago95#176]
When I click on menu inside Terminal, it appears like this one. The dropdown menu seems out of order. 

![Screenshot_2021-03-31_01-16-21](https://user-images.githubusercontent.com/81664946/113085238-ac6b3480-9209-11eb-9076-f57fd5349ecc.png)

I am running Linux Mint Xfce 20.1.

**Comment by EMH-Mark-I** [comment]
Issue is now addressed.

**Comment by david-zika** [comment]
On Linux Mint 21.1 Cinnamon the problem is here again. It looks the same as above. I can't send screenshot, the print-action doesn't work when is submenu shown (why?).

**Comment by bfc-rd** [comment]
@grassmunk I am having the same issue on Xfce 4.20 with the master branch. I tried adding margin to the top of `menuitem > window`, but that has no effect. I also tried tricks like `border-top: 5px solid transparent`. No luck.
