### ISSUE TITLE
[ChangeRequest] Windows98 and Windows2k theme

### ISSUE THREAD

**Issue by corasaniti** [grassmunk/Chicago95#181]
It would be nice to have the Windows98 and Windows2000 theme, icons and colors...
Thank you

**Comment by grassmunk** [comment]
This theme borrows heavily from Windows98 icons as well. Other than the color scheme and gradient there's not much to change. You might be able to achieve the look with a Windows98 XFWM/GTK theme and the Chicago95 icons.
