### ISSUE TITLE
Can't get Chicago95 Plus GUI.py to run in Pop OS 20.10

### ISSUE THREAD

**Issue by BalooRJ1** [grassmunk/Chicago95#184]
Can't get it to run. Installed python3-numpy, python3-fonttools, python3-svgwrite, and inkscape packages from the Ubuntu repo. Here is the errors I get. Chicago95 Plus log in attached file.

Terminal errors:

[MakePreview] Generating Preview Image
ERROR    :: parse_font_files       :: Font /home/baloo/Documents/Chicago95-master/Icons/Chicago95-tux/mimes/scalable/gnome-mime-application-x-font-ttf.svg cannot be read: Not a TrueType or OpenType font (bad sfntVersion)
[MakePreview] Metrics... OK
Traceback (most recent call last):
  File "/home/baloo/Documents/Chicago95-master/Plus/PlusGUI.py", line 872, in open_file
    self.preview_image = MakePreview(self.theme)
  File "/home/baloo/Documents/Chicago95-master/Plus/PlusGUI.py", line 110, in __init__
    self.set_fonts()
  File "/home/baloo/Documents/Chicago95-master/Plus/PlusGUI.py", line 171, in set_fonts
    self.lfMessageFont = self.get_font(self.msgfont)
  File "/home/baloo/Documents/Chicago95-master/Plus/PlusGUI.py", line 384, in get_font
    return self.get_font("Noto-Sans-Regular")
  File "/home/baloo/Documents/Chicago95-master/Plus/PlusGUI.py", line 384, in get_font
    return self.get_font("Noto-Sans-Regular")
  File "/home/baloo/Documents/Chicago95-master/Plus/PlusGUI.py", line 384, in get_font
    return self.get_font("Noto-Sans-Regular")
  [Previous line repeated 988 more times]
  File "/home/baloo/Documents/Chicago95-master/Plus/PlusGUI.py", line 360, in get_font
    if fontname in ["MS Sans Serif", "MS Serif", "‚l‚r ‚oƒSƒVƒbƒN"]:
RecursionError: maximum recursion depth exceeded in comparison
[chicago95_plus.log](https://github.com/grassmunk/Chicago95/files/6386201/chicago95_plus.log)

**Comment by grassmunk** [comment]
Try putting the nights theme in its own folder and running the script from that folder not your home or documents folder. Can you send me a copy of the theme again so I can test it out?

**Comment by BalooRJ1** [comment]
Thanks @grassmunk! Here is a copy of the theme again: https://web.archive.org/web/19970328001115/http://www.sega.com/games/downloads/themes.html

That being said, I currently can't get any theme to work. The NiGHTS theme is contained in its own folder with resources. That does not seem to change the errors I am getting.

**Comment by BalooRJ1** [comment]
Hi @grassmunk, any updates on this?

**Comment by grassmunk** [comment]
I'm not sure what issue you were having. POP_OS is not supported but here's the theme (I just generated this):

[Nights_(256_color)_Chicago95.tar.gz](https://github.com/grassmunk/Chicago95/files/6518418/Nights_.256_color._Chicago95.tar.gz)

**Comment by PineconeMonster** [comment]
I had the same issue but I fixed it by installing alsa-utils which has aplay in it
