### ISSUE TITLE
Gnome Shell

### ISSUE THREAD

**Issue by fishears** [grassmunk/Chicago95#19]
Please would you consider theming Gnome Shell. The GTK3 theme is amazing but incomplete on my Ubuntu Gnome desktop...

**Comment by EMH-Mark-I** [comment]
I apologize for the late reply, but if it's at all possible could you give it another go? I've made some updates to the theme and have been trying to get it back into working order. There's still a lot that needs to be done.

I'm not sure how well the theme will run under the GNOME shell itself since XFCE is the preferred environment. However I just installed gnome-terminal to see how it handles with the theme and it appears to be well for the most part. Terminal tabs are a bit too big however so I'll try to see if there's anything to fix that in the future. (Same with the XFCE terminal too.)

I'll be closing the ticket soon since I'm trying to clean these old issues that have just hung around.

**Comment by fishears** [comment]
Thanks for the updates. the theme looks great on GTK3 in GNOME Shell 3.26.2
The issue I raised was really in respect of the "shell" (top-bar on the desktop) aspect of GNOME rather than the window manager (GTK3). Now I re-read my issue I can see that I wasn't very clear (sorry). If GNOME Shell isn't in your project's scope then that's fine - it's still a great theme!!!

**Comment by EMH-Mark-I** [comment]
You're welcome!

I don't know if it's in the scope or not, but XFCE is the preferred environment. That would probably be different if there were a whole lot more people working on this!

**Comment by grassmunk** [comment]
Personally I would love to have a gnome shell. This project wasn't supposed to be '100% windows 95 total conversion' but more a theme to make it look like what it would look like today. Hence the GTK3 theming. 

Unfortunately i don't have the skills/time to work on this but i'd love this.

**Comment by grassmunk** [comment]
Looking at https://github.com/B00merang-Project/windows-95 I'm thinking we could get rid of my GTK3 theme and use this one. I haven't done a comparison between the two just a thought.

**Comment by EMH-Mark-I** [comment]
> Looking at https://github.com/B00merang-Project/windows-95 I'm thinking we could get rid of my GTK3 theme and use this one. I haven't done a comparison between the two just a thought.

I don't want to cast any shade on another project, but I can see a number of inconsistencies from the screenshot alone.

Now I'm curious how that frame in the panelbar is able to encompass the clock and status icons. I would love to have that here!

A rewrite would probably be a benefit. I do have a rewrite of the GTK3 buttons which should fix a lot of button sizing troubles, I hope. And resized the GTK3 menus to match the GTK2, and a touch up to those popvers.

**Comment by fishears** [comment]
you know that's cinnamon panel in the screenshot right?

**Comment by EMH-Mark-I** [comment]
I didn't even know!

**Comment by Elbullazul** [comment]
if you're still willing to add a shell theme I can help you with it

**Comment by grassmunk** [comment]
I would love a 'Windows95 Inspired' Gnome Shell Theme. Feel free to submit a PR.

**Comment by Elbullazul** [comment]
work so far:
![Screenshot from 2019-07-18 16-03-01](https://user-images.githubusercontent.com/15310985/61488592-9f93a800-a976-11e9-90e7-7761edbb6ad6.png)
![Screenshot from 2019-07-18 16-09-41](https://user-images.githubusercontent.com/15310985/61488593-9f93a800-a976-11e9-84ad-393a45e0f205.png)
![Screenshot from 2019-07-18 16-09-49](https://user-images.githubusercontent.com/15310985/61488594-9f93a800-a976-11e9-830e-5768f77360e1.png)


I based this on the default SCSS and vectorized some assets to have a better resolution:
[assets-render.zip](https://github.com/grassmunk/Chicago95/files/3408281/assets-render.zip)

**Comment by grassmunk** [comment]
How far were you able to get with this @Elbullazul ?

**Comment by Elbullazul** [comment]
I believe it was merged:

https://github.com/grassmunk/Chicago95/pull/82

**Comment by grassmunk** [comment]
Yes, yes it was lol. Thanks!
