### ISSUE TITLE
Inkscape Error with PlusGUI.py

### ISSUE THREAD

**Issue by oliversandli** [grassmunk/Chicago95#190]
I was trying to install the Hackerz theme (https://archive.org/details/hackerz_202005) to test out the PlusGUI program, but inkscape is crashing. The bad command is at the bottom of the output log below.

After some experimentation by running the command on its own (below), it seems that `FileQuit` is causing the crash. The command works fine, opening an image in inkscape, without `FileQuit`.

Test command: `inkscape -g --select=rect4 --verb="EditSelectSameFillColor;SelectionCombine;SelectionUnion;FileSave;FileQuit" ~/cloned-repos/Chicago95/Plus/chicago95_tmp_file.svg`

Output from PyGUI:
```text
chicago95/Plus > ./PlusGUI.py 
[MakePreview] Generating Preview Image
[MakePreview] Metrics... OK
[MakePreview] Fonts... OK
[MakePreview] Icons... OK
[MakePreview] Wallpaper... OK
[MakePreview] Buttons... OK
[MakePreview] Preview... OK
[MakePreview] Preview Generated
Installing theme with the following options:
Theme File: /home/oliver/Downloads/Hackerz Theme/Hackerz.theme
Inkscape Options:
	Colors: 32 Overlap: 1 Squaresize: 20
Install Directory: /home/oliver/cloned-repos/Chicago95/Plus
Paths:
	Cursor Path: /home/oliver/.icons/Chicago95_Cursor_Black
	Theme Path: /home/oliver/.themes/Chicago95
	Icons Path: /home/oliver/.icons/Chicago95
Install (checkbox) Options:
	Cursors: True
	Icons: True
	Wallpaper: False
	Sounds: False
	Colors: True
	Fonts: True
	Screensaver: False
Traceback (most recent call last):
  File "/home/oliver/cloned-repos/Chicago95/Plus/./PlusGUI.py", line 1207, in install_accept
    self.install_theme()
  File "/home/oliver/cloned-repos/Chicago95/Plus/./PlusGUI.py", line 1232, in install_theme
    self.theme.go(cursors=self.install_cursors, icons=self.install_icons, wallpaper=self.install_wallpaper,
  File "/home/oliver/cloned-repos/Chicago95/Plus/pluslib.py", line 155, in go
    self.generate_theme(cursors, icons, wallpaper, sounds, colors, fonts, screensaver)
  File "/home/oliver/cloned-repos/Chicago95/Plus/pluslib.py", line 268, in generate_theme
    self.create_icons()
  File "/home/oliver/cloned-repos/Chicago95/Plus/pluslib.py", line 972, in create_icons
    svg_icon_file = self.convert_icon(self.folder_names['icons'], self.folder_names['icons']+icon_filename)
  File "/home/oliver/cloned-repos/Chicago95/Plus/pluslib.py", line 2452, in convert_icon
    self.fix_with_inkscape( rgbs[rgb] , tmp_file )
  File "/home/oliver/cloned-repos/Chicago95/Plus/pluslib.py", line 2511, in fix_with_inkscape
    subprocess.check_call(args, stderr=subprocess.DEVNULL ,stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[b'/usr/bin/inkscape', '-g', '--select=rect4', '--verb', 'EditSelectSameFillColor;SelectionCombine;SelectionUnion;FileSave;FileQuit', '/home/oliver/cloned-repos/Chicago95/Plus/chicago95_tmp_file.svg']' died with <Signals.SIGSEGV: 11>.
```

**Comment by oliversandli** [comment]
Output from the test command, with `FileQuit`:
```text
Shortcut::read: invalid verb: DialogSpellcheck
select_by_id: Did not find object with id: rect4

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at https://inkscape.org/report
with a detailed description of the steps leading to the crash, so we can fix it.
[1]    11985 segmentation fault (core dumped)  inkscape -g --select=rect4
```

**Comment by grassmunk** [comment]
Interesting. Could you provide you OS, dirstro python and inkscape versions?

**Comment by oliversandli** [comment]
Sure.

OS: Manjaro 21.0.7
Python: 3.9.5
Inkscape: 1.1 (c4e8f9ed74, 2021-05-24)

**Comment by kenshen112** [comment]
`     || Chicago95         **
 ########  ##   ##       ****        
 ##  || ## ##   ## $$$$$$**** 
 ##  || ## ##   ##$$      ** 
 ########  ##   ## $$$$     
 ##  ||     #####      $$ **
 ##  ||||||||     $$$$$$  **
 ##                        

Traceback (most recent call last):
  File "/home/musungo/Chicago95/Plus/./ChicagoPlus.py", line 67, in <module>
    main()
  File "/home/musungo/Chicago95/Plus/./ChicagoPlus.py", line 65, in main
    plus.go(cursors=args.nocursors, icons=args.noicons, wallpaper=args.nowallpaper, sounds=args.nosounds, colors=args.nocolors, fonts=args.nofonts, screensaver=args.noscreensaver)	
  File "/home/musungo/Chicago95/Plus/pluslib.py", line 155, in go
    self.generate_theme(cursors, icons, wallpaper, sounds, colors, fonts, screensaver)
  File "/home/musungo/Chicago95/Plus/pluslib.py", line 268, in generate_theme
    self.create_icons()
  File "/home/musungo/Chicago95/Plus/pluslib.py", line 972, in create_icons
    svg_icon_file = self.convert_icon(self.folder_names['icons'], self.folder_names['icons']+icon_filename)
  File "/home/musungo/Chicago95/Plus/pluslib.py", line 2452, in convert_icon
    self.fix_with_inkscape( rgbs[rgb] , tmp_file )
  File "/home/musungo/Chicago95/Plus/pluslib.py", line 2511, in fix_with_inkscape
    subprocess.check_call(args, stderr=subprocess.DEVNULL ,stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[b'/usr/bin/inkscape', '-g', '--select=rect4', '--verb', 'EditSelectSameFillColor;SelectionCombine;SelectionUnion;FileSave;FileQuit', '/home/musungo/Chicago95/Plus/chicago95_tmp_file.svg']' died with <Signals.SIGBUS: 7>.
`

Arch Linux running Chicago95 plus CLI I get the same error trying to install any of these themes. https://archive.org/details/13themes

**Comment by grassmunk** [comment]
We only officially support Xubuntu, what is the exact error you get from inkskape when you run the command python tried to run?

In lieu of making you install the Xubuntu theme i've converted the themes each of you had issues with, you'll have to install them manually. 

[hackerz.tar.gz](https://github.com/grassmunk/Chicago95/files/6833363/hackerz.tar.gz)
[13themes.tar.gz](https://github.com/grassmunk/Chicago95/files/6833364/13themes.tar.gz)
