### ISSUE TITLE
Unclean uninstallation

### ISSUE THREAD

**Issue by robotertheman** [grassmunk/Chicago95#198]
I am having issues with XFCE after trying to get rid of Chicago95.
I decided I wasn't going to use it after a few days, and now that I've removed all files from .icons, .themes, .fonts, etc. I am now facing issues with AppMenu and context menus in windows.

The terminal now shows gaudy, ugly big icons instead of a context menu, and AppMenu won't display context for it. This happens on all applications with an embedded context menu. Some will show in AppMenu but still retain the ugly, big icons when they hadn't before.
![image](https://user-images.githubusercontent.com/46545671/130897521-5b5d9f10-15c1-4bf1-8752-90d075660999.png)

I don't know what the installer did, and I need help reversing it. Any information on what could be the issue?

**Comment by grassmunk** [comment]
Part of the install installs `~/.config/xfce4/terminal/terminalrc`. If a previous terminalrc file existed the file `~/.config/xfce4/terminal/backup.terminalrc.chicago95` will be created, you can return to the previous config with `cp ~/.config/xfce4/terminal/backup.terminalrc.chicago95 ~/.config/xfce4/terminal/terminalrc`
