### ISSUE TITLE
How to remove background color text below desktop icon?

### ISSUE THREAD

**Issue by niizam** [grassmunk/Chicago95#202]
I'd like to use transparent background color text instead green

**Comment by googkhan** [comment]
It defines in this line https://github.com/grassmunk/Chicago95/blob/9ecce83c194de6e7ef56fb5ad9b82bb7e261cb67/Theme/Chicago95/gtk-2.0/gtkrc#L565

**Comment by googkhan** [comment]
and this line, current xfdesktop chooses this by default https://github.com/grassmunk/Chicago95/blob/9ecce83c194de6e7ef56fb5ad9b82bb7e261cb67/Theme/Chicago95/gtk-3.0/gtk.css#L134

**Comment by niizam** [comment]
> and this line, current xfdesktop chooses this by default
> 
> https://github.com/grassmunk/Chicago95/blob/9ecce83c194de6e7ef56fb5ad9b82bb7e261cb67/Theme/Chicago95/gtk-3.0/gtk.css#L134


> It defines in this line
> 
> https://github.com/grassmunk/Chicago95/blob/9ecce83c194de6e7ef56fb5ad9b82bb7e261cb67/Theme/Chicago95/gtk-2.0/gtkrc#L565

Thank you very much sir
