### ISSUE TITLE
Chicago95 Plus! theme is not fully applied.

### ISSUE THREAD

**Issue by Rotary-FC** [grassmunk/Chicago95#204]
[Log.txt](https://github.com/grassmunk/Chicago95/files/7349396/Log.txt)

Not sure what to make of this, I have the required programs but how can I be missing a .DLL file?

**Comment by grassmunk** [comment]
Can you run it with debugging enabled and paste the logs?

**Comment by grassmunk** [comment]
No Follow-up closing
