### ISSUE TITLE
How to change the colorscheme without having a Microsoft Plus! theme file

### ISSUE THREAD

**Issue by teahwiz** [grassmunk/Chicago95#206]
How to change the colorscheme without a Microsoft Plus! theme file

**Comment by Fierelier** [comment]
It's not perfect, but you can use the recolor.py in extras, which I made for the project.

First, install the theme on your system, then install python3-pillow. Edit recolor.py to your liking, then run recolor.py using python3. The way recolor.py is configured on default, it will give you the color scheme of Windows 2000. Then change your theme both in Appearance and Window Manager to the new one.
