### ISSUE TITLE
Program icon appears one pixel higher than it should be

### ISSUE THREAD

**Issue by 0x5066** [grassmunk/Chicago95#213]
Hello!

I'm loving this theme so far, running this in a Manjaro VM as I'm planning to jump ship to Manjaro on my host.

I've noticed that the program icon in the title bar is positioned one pixel higher than it should be:
![winamp original_wkZreF0XA1](https://user-images.githubusercontent.com/38136789/146686369-e49fac3a-ac13-4b8c-9e78-0e5d4e107550.png)
(On the right is my Winamp skin that emulates Windows Classic as well)

Normally it should be set a pixel lower, I tried to find where that sits in the css files but wasn't lucky.

**Comment by grassmunk** [comment]
Honestly I'm not sure if this is a theme issue or if the icon isn't centered in it square. @EMH-Mark-I any ideas?

**Comment by EMH-Mark-I** [comment]
Yeah, that'll be the XFWM4 window manager theme. I can adjust the menu-active.xpm and menu-inactive.xpm to address the issue.

**Comment by 0x5066** [comment]
Hi!

I haven't forgotten about this and only now got around to check if the latest commit addresses the issue, which it thankfully does.

Thank you so much!
