### ISSUE TITLE
Chicago95 Plus

### ISSUE THREAD

**Issue by gitdrug** [grassmunk/Chicago95#214]
For Chicago95 Plus Support for .msstyles would be nice because i want to use the zune theme from windows xp but it is a .msstyles and not .theme so .msstyles support for Chicago95 Plus would be great.

**Comment by gitdrug** [comment]
Bump

**Comment by grassmunk** [comment]
Honestly i'm not sure if this is something I can support. The original plus script is made up of a library that can parse the .theme file and it looks for specific things in that file. You might want to ask on a Windows XP theme git: https://github.com/B00merang-Project/Windows-XP
