### ISSUE TITLE
Panel font spacing

### ISSUE THREAD

**Issue by pkfbcedkrz** [grassmunk/Chicago95#219]
The label is a bit far from the icon in panel buttons:
![panel](https://user-images.githubusercontent.com/97207250/148322467-89cc2cd9-7cf1-4b3f-af03-757bcd3808d1.png)

DE: Xfce 4.16
Distro: Arch Linux
Gtk: 3.24

**Comment by EMH-Mark-I** [comment]
Hmm, you're right. I didn't really notice this. I'll try to fix it because it's a bit irritating now.

**Comment by EMH-Mark-I** [comment]
This looks pretty close now. (Top panel is Windows 95. Bottom panel is XFCE.)
![taskbar](https://user-images.githubusercontent.com/28378002/148715375-bcb45eb7-f600-4830-a5ce-921fee4f3c2d.png)

**Comment by pkfbcedkrz** [comment]
It looks very authentic now - thanks!

I would suggest removing line 42 in https://github.com/grassmunk/Chicago95/blob/master/Theme/Chicago95/gtk-3.0/apps/whiskermenu.css#L42 and simply using the default system font. Because of the issues mentioned in #218, MS Sans Serif will not be supported going forward. Note how the word "Oracle" is oddly spaced in the bottom panel of your picture - there is too much space around the "r," and too little around the "l" such that the "c" sticks to it. 

Removing line 42 and using cronyx Helvetica from #218 as the system font, the panel looks like the third row in this image. Note the "Start" font is identical to the Win95 original, and the word "Oracle" is properly spaced:
![start](https://user-images.githubusercontent.com/97207250/148933886-e7c66ceb-ce48-4ee1-b695-11bc17302cbf.png)

**Comment by EMH-Mark-I** [comment]
Thanks, I'll try out that font. I haven't had time to install it yet. I might end up adding Helvetica as the default and keep the MS Sans font as one of the fallback options.
