### ISSUE TITLE
GTK FileChooser bookmarks text invisible

### ISSUE THREAD

**Issue by phil294** [grassmunk/Chicago95#220]
![chicago95-themed file picker](https://waritschlager.de/share/22C48F3D894AB430199747CE47693B11.png)

Is this problem specific to my installation? Does the file picker work for you guys? I've had this issue for many months now, but not in earlier times. Unfortunately, I cannot recall what made it break, and I can't rule out it was my fault. But at least it's exclusive to Chicago95.

I can work around this by changing `gtk-3.0/gtk-widgets.css` the color value at
```css
  .sidebar list {
    color: @selected_fg_color;
```
to something different.

In comparison, this is how it looks in Adwaita:
![adwaita-themed file picker](https://waritschlager.de/share/355253FCCADC2E8B3FEA541708EA6001.png)

system:
```
OS: Manjaro 21.2.1 Qonos
Kernel: x86_64 Linux 5.4.169-1-MANJARO
GPU: Intel Corporation HD Graphics 530 (rev 06)
```

**Comment by EMH-Mark-I** [comment]
The file picker sidebar should have a grey background, like this screenshot:
![file_picker](https://user-images.githubusercontent.com/28378002/148710028-b82cdec6-3853-4d66-94c5-254009ef8dd2.png)
If you have anything in `~/.config/gtk-3.0/gtk.css`, then go ahead and delete it or back that file up somewhere else. Then log out and log back in for the change to apply.

**Comment by EMH-Mark-I** [comment]
Oh, you might also re-download and install the theme again. I don't know if you may have made a change to one of the files that could be causing that too.

**Comment by phil294** [comment]
> The file picker sidebar should have a grey background, like this screenshot: [file_picker] If you have anything in `~/.config/gtk-3.0/gtk.css`, then go ahead and delete it or back that file up somewhere else. Then log out and log back in for the change to apply.

It works! I did not know about the `~/.config/gtk3.0/gtk.css` thing.

For context: I searched for the origins of the file and found it: Back in 2018, Chicago95 advice to put [Extras/override/gtk.css](https://github.com/grassmunk/Chicago95/blob/2f383092ce96a82ee358fc40a196a7ced53379fb/Extras/override/gtk.css) into [the gtk3.0 folder](https://github.com/grassmunk/Chicago95/blob/2f383092ce96a82ee358fc40a196a7ced53379fb/INSTALL.md). This file seems to have been removed at some point. But there are now [other override gtk.css files](https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md#-gtk3-override-configuration-). So it was not really my fault after all - I'll put a suggestion into the uninstaller issue  #149.

Thanks for your help!
