### ISSUE TITLE
Dark Theme for Plus

### ISSUE THREAD

**Issue by OpeningCredits** [grassmunk/Chicago95#221]
I was digging around the internet and seemingly there was a dark theme available for Plus, I was wondering if anyone knew where to get it?
![image](https://user-images.githubusercontent.com/94167392/148647098-e3cde8d0-c29a-4772-a23d-db5606f05b7a.png)

If it isn't available, I don't suppose anyone would care to take on the challenge of making it themselves?

**Comment by grassmunk** [comment]
I'm not sure which theme that is specifically but you can browse https://archive.org/details/windowsdesktopthemes to find themes and then edit the `.theme` file to change it to the colors you want.
