### ISSUE TITLE
Window content is one pixel too far away from all sides

### ISSUE THREAD

**Issue by 0x5066** [grassmunk/Chicago95#223]
Hi again!

I've discovered another issue in terms of accuracy, I don't know if the title makes sense so I'll attach an image here that hopefully explains it in a better way (if you zoom in far enough)

Basically, the border of the window extends one pixel too far from all sides in Chicago95, instead of being relatively closer (that is for resizable windows, I don't know if there's a separate state for statically sized windows).

![image](https://user-images.githubusercontent.com/38136789/151677817-45d96164-7f87-4aa5-90f1-c03ad12109c0.png)
In the image, I have Wine Desktop at 640x480 and Milkdrop 1 from a Windows 98 VM run inside PCem, and you'll notice that the window on the right has it's content closer to the window borders than Chicago95 does.

I hope this was explained well enough, and if not, I'll try to explain it better with images.

Thanks in advance!

**Comment by EMH-Mark-I** [comment]
Just to clarify, is this what you're reporting?
![borders](https://user-images.githubusercontent.com/28378002/155855843-4fd889c0-010e-4319-a9a4-2141ba909a4e.png)

Thanks

**Comment by EMH-Mark-I** [comment]
I've addressed this, however I noticed that there are some applications that will still include an additional pixel between the border and its content. I don't think there's anything I can do to counter that.

Here's an example of Liferea RSS reader. I used the inspector tool to highlight the toolbar, which shows that it's the correct distance from the window border, while the treeview below introduces an extra pixel.

![counting_pixels](https://user-images.githubusercontent.com/28378002/158722946-01c0b5d9-cc9a-4a15-873e-6d94b871fe1d.png)

**Comment by 0x5066** [comment]
(Can't reopen the issue but I still think it's worth to point out regardless)
It's great! Though where I put the red line, is where it's one pixel too far away from the title bar (see my first screenshot and the right window), as it should be closer, this is something I also got wrong for a very long time in my Winamp skin as I had blindly assumed without double checking if that's correct, as it made sense to me, but I was wrong.

![image](https://user-images.githubusercontent.com/38136789/160915426-209669cd-2dd5-40e2-b845-4cc2c3a3c942.png)

I'll open a separate issue as the title bar controls seem oddly misplaced.
