### ISSUE TITLE
4k / highdpi issues

### ISSUE THREAD

**Issue by machineboy2045** [grassmunk/Chicago95#224]
I'm loving this theme! But I did notice a few small issues on my 4k display using XFCE and 2x scaling:

* Top left window corner is broken/too short. I believe it was `Chicago95/xfwm4/top-left-active.xpm`. 
* Mouse pointers are tiny / not scaled
* Application icons have grey background in the window title bar when the window is active.
* The close button has a transparent line at the top. I can see the blue title bar bleeding through on active windows.

![chicago95](https://user-images.githubusercontent.com/4087667/154105874-26e923c6-b3b7-49da-858c-7c12a34c4388.png)

I was able to fix most of the issues but I don't know how to properly save .xpm files. I lose the transparency when I save them. I would be happy to make a pull request if you can point me to documentation on how to edit/save .xpm files.

**Comment by EMH-Mark-I** [comment]
Hi @machineboy2045,
Thanks for bringing up these issues. I'll have to look into them to address as time permits.
