### ISSUE TITLE
How do I disable the Windows95 text from terminal

### ISSUE THREAD

**Issue by ReShout876** [grassmunk/Chicago95#233]
I dont wanna have it anymore and i dont know how to remove it, help

**Comment by EMH-Mark-I** [comment]
Hi @ReShout876 
In your home directory is a hidden `.bashrc` file. Open that file, scroll down to the bottom, and remove the following lines: (Note: Don't delete the file, just delete the following text inside of it.)

```
# Emulate an MS-DOS prompt in your Linux shell.
# Laszlo Szathmary (jabba.laci@gmail.com), 2011
# Project home page:
# https://ubuntuincident.wordpress.com/2011/02/08/emulate-the-ms-dos-prompt/
#
#
# Modified by Soldier of Fortran
#
# Add to you ~/.bashrc file with: 'source ~/.themes/95/bashrc'

function msdos_pwd
{
    local dir="`pwd`"

    echo $dir | tr '/' '\\'
}

export PS1='C:`msdos_pwd`> '

echo 
echo
echo "Microsoft(R) Windows 95"
echo "   (C)Copyright Microsoft Corp 1981-1996."
echo
```

**Comment by ReShout876** [comment]
It worked!
Much appreaciated!  
![image](https://user-images.githubusercontent.com/63971777/160658087-861f0846-9a02-41c3-940e-313db8359be2.png)
