### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by ReShout876** [grassmunk/Chicago95#236]
Hello.
I wanna know how to make this:

![image](https://user-images.githubusercontent.com/63971777/163007953-fe94ba40-93c7-453d-b8b2-023c6327569b.png)
(from the repo's screenshots)

My current "menu" is like this:

![image](https://user-images.githubusercontent.com/63971777/163008164-46667590-3b79-48d6-a0ae-097378f82fea.png)

(using debian 11)

**Comment by kevgrig** [comment]
I had a similar issue although on Fedora, but check that out: https://github.com/grassmunk/Chicago95/issues/228

**Comment by ReShout876** [comment]
@kevgrig interesting, but I am on Debain, not Fedora...

**Comment by ReShout876** [comment]
Oh ye, now I learn't how to do it, thanks for the help!
