### ISSUE TITLE
Confusion with Thunar appearance vs Screenshots

### ISSUE THREAD

**Issue by shadowdragon625** [grassmunk/Chicago95#239]
Hello! I just recently compiled and installed Chicago95 to my Arch xfce4 install.

I noticed that my File Manager application, Thunar, looks different compared to the ones in the screenshots supplied on the main page.

Is there a way to replicate the screenshot image of Thunar, or is there another file manager that I must install to copy that look (and maybe provide an example of the icon spinner in use too?)

Thanks.

**Comment by EMH-Mark-I** [comment]
Can you take a screenshot of it? I suspect you are using one of the newest versions that implements some newer features. This will likely affect the current Thunar theming, which is for version 1.8.14 and below (until you reach the old GTK2 version, which I can't re-call.)

**Comment by shadowdragon625** [comment]
Right, yes! I forgot to do that the first time, I apologize for that.

According to the screenshots on the front page, this is what the file manager should look like
![Chicago95_Desktop](https://user-images.githubusercontent.com/67454590/169177228-f53b1558-5cb5-462d-8b6f-361d51b2408f.png)

Here's what mine look like

![image](https://user-images.githubusercontent.com/67454590/169177304-45e19c1a-65cc-49aa-a1df-1e15927ca1a8.png)

Is it another file manager program that you are using to make this work? Or is the screenshot is what Thunar is supposed to look like?

**Comment by EMH-Mark-I** [comment]
Sorry about the month long followup delay. I've just finished moving and haven't been able to keep up with my Internet activities.

The screenshot of your Thunar file manager appears to be the default Thunar configuration. You can change the layout of Thunar in the following manners.

**Icon View**
![icon_view](https://user-images.githubusercontent.com/28378002/173241879-c89204a1-109e-46b8-8cb7-768ecbb8fc3e.png)
- Open Thunar, press Ctrl+1 from your keyboard _or_ click from the menubar _View > Icon View_
- From the menubar click _View > Location Selector > Uncheck either Pathbar or Toolbar style_
- From the menubar click _View > Side Pane > Uncheck either Shortcuts or Tree_

**Compact View**
![compact_view](https://user-images.githubusercontent.com/28378002/173242154-e17a55b5-53dc-44f0-b900-605c4ed70044.png)
- Open Thunar, press Ctrl+3 from your keyboard _or_ click from the menubar _View > Compact View_
- From the menubar click _View > Location Selector > Uncheck either Pathbar or Toolbar style_
- From the menubar click _View > Side Pane > Uncheck either Shortcuts or Tree_

**List View with side pane**
![list_view](https://user-images.githubusercontent.com/28378002/173242258-2126a6f9-d57e-436a-b4fe-b7d3847ebbe6.png)
- Open Thunar, press Ctrl+2 from your keyboard _or_ click from the menubar _View > List View_
- From the menubar click _View > Location Selector > Uncheck either Pathbar or Toolbar style_
- From the menubar click _View > Side Pane > Enable Tree side pane_

**Additional Notes**
You can adjust the size of the folder and image icons in Thunar from your keyboard with "Ctrl +" or "Ctrl -" or from the menubar _View > Zoom In or Zoom Out_

If you accidentally disable the Thunar menubar, you can press Ctrl+m from your keyboard to re-enable it.

**Comment by shadowdragon625** [comment]
Yes, that worked! Thank you so much. Sorry I took a bit to reply as well, I was busy with college summer courses.

I feel like these should be added to the setup stage once the themes have been implemented, the default does look pretty cool though, but I prefer the Windows 95 version.

Thanks again for this, and hope your move may benefit you in the future ^^
