### ISSUE TITLE
Windows95 sounds

### ISSUE THREAD

**Issue by vitacell** [grassmunk/Chicago95#242]
Please, make some guide or "how-to" for replicate the full Windows95 experience for sounds, applying it on XFCE. Error, warning, hardware input/remove, battery, browsing, log-off...As only startup sound is present.

**Comment by grassmunk** [comment]
Does this no longer work: https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md#startup_sound

**Comment by BalooRJ1** [comment]
@vitacell:

Open Settings > Appearance and click on tab Settings

Make sure both Event Sounds are enabled (checked):

    Enable event sounds
    Enable input feedback sounds

You can test these sounds with the following command: canberra-gtk-play -i "sound name" 

We can use some of the following commands to test:
desktop-login
desktop-logout

For the startup sound, you can add into the Session & Startup in XFCE the following command to play on login: canberra-gtk-play -i desktop-login

HOWEVER, it seems that on most (if not all) Linux distros, the way canberra-gtk works is that the systems operate much too quickly on shutdown or with command notifications to play the full sound. I have them enabled, but I'll get half of a sound in a dialogue window, or it is very garbled. This has nothing to do with Chicago95 specifically, but everything to do with Canberra.
