### ISSUE TITLE
works for steam deck?

### ISSUE THREAD

**Issue by Joenzii** [grassmunk/Chicago95#247]
title

**Comment by EMH-Mark-I** [comment]
I don't think so? The Chicago95 theme primarily works for the XFCE desktop environment. There is some theming work done for MATE and Cinnamon desktops too, but they're not near as complete.
I haven't used the Steam desk environment, but I'm going to hazard that it probably won't look right there.
Now if you're able to apply the theme, it would certainly work for most GTK based applications.

**Comment by Mitchykins** [comment]
Looking on wikipedia, the default DE for the Steam Deck is KDE Plasma. Unless you get Xfce on Steam OS, your other option is to install another linux distribution with Xfce onto the device.

**Comment by grassmunk** [comment]
Yeah, even the icons won't work too well due to the way KDE handles Icons and theming. I would love to get the time to make a KDE theme for this.

**Comment by Joenzii** [comment]
> Yeah, even the icons won't work too well due to the way KDE handles Icons and theming. I would love to get the time to make a KDE theme for this.

would be awesome if you could very interested
