### ISSUE TITLE
Chicago95 does not change wallpaper

### ISSUE THREAD

**Issue by Xopek-Endurance** [grassmunk/Chicago95#248]
My system: Xubuntu 22.04, Xfce Version: 4.16 GTK+ Version: 3.24.33

When I try to change wallpaper with Chicago95 Plus! GUI, it does not work, and Terminal gives me error: 

> Property "/backdrop/screen0/monitorVirtual1/workspace0/last-image" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.

**Comment by grassmunk** [comment]
This is a hack at best for that script. If the background doesn't change you'll have to set it manually from the theme folder. This is due to the way screens are managed.
