### ISSUE TITLE
Eclipse huge scrollbars

### ISSUE THREAD

**Issue by davisvdiniz** [grassmunk/Chicago95#249]
Any ideas on how I could fix this?
![image](https://user-images.githubusercontent.com/108399514/177554663-4f22d654-7d77-4d63-bc78-fdcb80ff1fc7.png)

**Comment by EMH-Mark-I** [comment]
Yeah this application looks like its attempting to apply its own styling, but is doing a bad job at it. I don't have eclipse IDE, but is there a way to disable styles or themes to allow the system default theme to apply (or just select a built in theme for eclipse)? It's probably not possible, and I wouldn't have a way to fix this unfortunately.
