### ISSUE TITLE
Issues with changing installed themes from Plus. 

### ISSUE THREAD

**Issue by CounsellorPolonius** [grassmunk/Chicago95#251]
First of all here are the machine specs. I am running Devuan 4 and XFCE 4.16. It's in a VM. 
![nefoetc](https://user-images.githubusercontent.com/82978856/179404106-4aafc5ae-109d-4363-9491-439641dd5f34.jpg)

I'm having an issue when changing themes in Chicago95 Plus. After installing the various themes when I go to change it via XFCE --> Appearance not all the colors change. Here is an example of what I mean. 

![pic1](https://user-images.githubusercontent.com/82978856/179403922-ef593988-6d1d-4bd6-8957-c6332aa42fda.png)
This is it normally. 

When I go to appearance to change it to another theme not all the colors change. 
![pic2](https://user-images.githubusercontent.com/82978856/179403979-e9b7253a-d8b5-4588-a2b3-e9b984bf62ec.png)
The colors around the border as well as inactive window color don't change and stay the same from the previous theme. 

Here's another example. It is purple around the window when it should be a shade of blue.
![pic3](https://user-images.githubusercontent.com/82978856/179404091-15d2d218-65be-4511-8f2b-f1559623add6.png)

My only workaround is to just re-install the theme via Plus each time I want to switch but I have a separate issue with Plus not working right that makes this annoying to do each time (not all the colors switch). Any ideas on where to look to fix this? I get Devuan isn't supported but any help would be appreciated, at the very least where to look to fix this. 

When I installed the theme via Plus originally, the only option I had selected was to install colors. I didn't touch anything else. 

I have also checked the gtk.css in each theme folder looking for the old colors but they don't seem to be there.

**Comment by grassmunk** [comment]
This is because you need to change all themes:

1. The Icon Theme 
2. The GTK Theme
3. The Window Manager Theme

You're only changing the GTK theme which is causing this effect.

**Comment by CounsellorPolonius** [comment]
Huh, I was not aware they were separate things. Looking at the neofetch I can't believe I didn't notice that. Thanks. I can also confirm that Chicago95 works great on Devuan. Thanks again!
