### ISSUE TITLE
How to Get Rid of These Borders/Outlines for These Plugin Icons?

### ISSUE THREAD

**Issue by SaiTheCyclone** [grassmunk/Chicago95#260]
How do I get rid of these borders/outlines on these plugin icons (excluding the clock)? Suddenly appeared out of no where and I have no idea what I did! Sorry, don't know where else to ask.
![Screenshot_2022-08-23_20-12-16](https://user-images.githubusercontent.com/61062544/186289236-2c8dfeff-9427-4410-8372-3d8eb3a02233.png)

**Comment by EMH-Mark-I** [comment]
That's new. Can you tell me what version of XFCE you're using?
You can open a terminal and type `xfce4-panel --version`
Thanks!

**Comment by SaiTheCyclone** [comment]
I no longer have this issue myself after reinstalling Chicago95 after performing a factory reset on my computer (after some issue, but not related to the theme itself).
I believe I was running XFCE 4.16.3 and still running it to this day.

**Comment by EMH-Mark-I** [comment]
That's good to hear!
