### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by rajabebek** [grassmunk/Chicago95#263]
Windows xp please

**Comment by BalooRJ1** [comment]
The only great WindowsXP theme exists for the Trinity Desktop Environment running on the Debian-based distro Q4OS. If you are interested in a WinXP look, that will get you near identical, including Plymouth boot screen, login screen, sound package, icon package, etc.

**Comment by grassmunk** [comment]
There's other better WindowsXP themes around and we focus on Windows 95/98 sorry.
