### ISSUE TITLE
How to remove the white border

### ISSUE THREAD

**Issue by Benj-Escrupulo** [grassmunk/Chicago95#265]
![Screenshot from 2022-09-27 13-26-19](https://user-images.githubusercontent.com/114464598/192440820-73807a4b-c38a-4314-8b6a-b9e77248b634.png)
Hi. I installed the Chicago95 using the python script and use it as my main theme for a few weeks and now I want to delete all the Chicago95 folders, etc. Thank you in advance for your help :)

**Comment by grassmunk** [comment]
You should be able to remove the Chicago95 folder from `~/.themes` and change your theme to something else.
