### ISSUE TITLE
How do I set the plymouth theme on Arch Linux?

### ISSUE THREAD

**Issue by FormalSnake** [grassmunk/Chicago95#271]
Hi, I am using XFCE on Arch linux, and I am stuck on some commands listed here:
https://github.com/grassmunk/Chicago95/tree/master/Plymouth

**Comment by EMH-Mark-I** [comment]
I'm not very familiar with Arch Linus. Were you able to install Plymouth first? There is  part of the ArchWiki that is linked, which demonstrates how to install Plymouth. https://wiki.archlinux.org/title/Plymouth#Installation

After that, you can copy the Chicago95 Plymouth theme over `cp -r Chicago95/Plymouth/Chicago95 /usr/share/plymouth/themes/` then run `plymouth-set-default-theme -R Chicago95`

**Comment by FormalSnake** [comment]
That worked, thanks!
