### ISSUE TITLE
Missing module 'gi'

### ISSUE THREAD

**Issue by cosmopolitics** [grassmunk/Chicago95#273]
File "/home/cosmo/Downloads/Chicago95-master/./installer.py", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

i have no idea what gi is or how to resolve the error

**Comment by bgstack15** [comment]
You can install package "python3-gi" which can be done with apt, yum, pacman, or similar, for your distro. GI stands for "gobject introspection" which allows programs to control GTK+ objects. GTK+ is the graphical toolkit used by the vast majority of components that are used to display the Chicago95 theme.
