### ISSUE TITLE
Xfce 4.18 panel items/icons issue

### ISSUE THREAD

**Issue by Lihvar** [grassmunk/Chicago95#286]
Im having issues with Xfce 4.18 (on arch). I did a clean install of Chicago95 and also used the command `xfce4-panel-profiles load Extras/Chicago95_Panel_Preferences.tar.bz2` and my panel looks nothing like the screenshots, the panel items/icons like notification, network and sound all have borders around them, otherwise the whole theme package is awesome!

![panel-issue](https://user-images.githubusercontent.com/33036901/234886217-92511245-8146-4b30-a781-07321dab332c.png)

**Comment by Lihvar** [comment]
I have fixed by creating a `gtk.css` inside `.config/gtk-3.0`

Like so:
![panel-fix](https://user-images.githubusercontent.com/33036901/235003981-e55c48b9-1400-4bc7-95bf-6953d1287187.png)

**Comment by CarterSnich** [comment]
Didn't worked anymore
