### ISSUE TITLE
Please add support for GTK 3.20+

### ISSUE THREAD

**Issue by DocMAX** [grassmunk/Chicago95#3]
Please add support for GTK 3.20+

**Comment by tjohnman** [comment]
For future reference, this fork has 3.22 support:
[https://github.com/AdrianoML/Chicago95](https://github.com/AdrianoML/Chicago95)

Thanks @grassmunk for creating this great theme and @AdrianoML for the rewrite to GTK 3.22.

**Comment by AdrianoML** [comment]
If grassmunk is still around, I can make a pull request

**Comment by grassmunk** [comment]
Hi All, 

Yes I'm here, though sporadically, I would love a pull request.

I've also incorporated the changes outlined here: https://www.reddit.com/r/unixporn/comments/68i7ut/xfce_classic_redmond_grey_theme_updated/

**Comment by grassmunk** [comment]
Ok I went and did some testing with Mousepad (one of the first gtk3 apps in ubuntu) with your fork and noticed that it didn't display properly. Here's with Chicago95 current (without your changes): 
<img width="1440" alt="screen shot 2017-05-03 at 3 11 05 pm" src="https://cloud.githubusercontent.com/assets/3452173/25684126/885dcf40-3014-11e7-9391-6c773d5bb53d.png">

Notice the menus and the arrow keys don't seem to work. And neither does the file selector.

Compare that with the current Chicago95 theme:
<img width="1440" alt="screen shot 2017-05-03 at 3 11 34 pm" src="https://cloud.githubusercontent.com/assets/3452173/25684147/aac2eaac-3014-11e7-8f5e-156761c2bcaa.png">

**Comment by AdrianoML** [comment]
Are you using gtk 3.18? The changes made for 3.20 unfortunately make it incompatible with previous versions. I've tried it on ubuntu 16.04 which uses gtk 3.18, and it has the same issues.

We could still try and distribute both versions.

**Comment by grassmunk** [comment]
Good catch. Yeah I was using an older Ubuntu. Just install 17.04 and tested it out. Looks great but had some questions/comments. 

1. When looking at lists (like in Whisker, but alsp in the choose file dialogue for mousepad) there's a thin line between items. Any way to get rid of that line or is that a gtk3 requirements? Here's an example screenshot:
![screenfetch-2017-05-03_21-49-57](https://cloud.githubusercontent.com/assets/3452173/25690894/a60743d8-304a-11e7-8c58-087d6565c965.png)

2. There's a 'bevel' around windows interiors. For example look at mousepad and terminal in this screenshot. There's this 2-3 pixel border around the internal window in both when there shouldn't be any. 
![screenfetch-2017-05-03_21-48-46](https://cloud.githubusercontent.com/assets/3452173/25690914/e09f64a8-304a-11e7-9620-8b43271d0588.png)

Compare with my example screenshots posted previously which doesn't have the window bevel or compare to screenshot of the original notepad in windows 95.
![image](https://cloud.githubusercontent.com/assets/3452173/25690963/5dbc6904-304b-11e7-8f51-c8d9f93ce364.png)

**Comment by AdrianoML** [comment]
The beleveling was caused because all those elements where embedded on a notebook. I have now found out that gtk sets a .frame style for notebooks that are supposed to be "floating around" rather than integrated in a window. I've commited a patch where I don't add a frame nor some padding to notebboks without a .frame style. This seems to solve the issue. (although sometimes the effect loked cool)

**Comment by grassmunk** [comment]
Thanks for doing this!
