### ISSUE TITLE
The tabs in xfce4-terminal do not indicate which one is active

### ISSUE THREAD

**Issue by bmintz** [grassmunk/Chicago95#30]
This is almost a dealbreaker for me. I use the terminal tabs in xfce4-terminal quite a lot, and I can't tell which tab I'm currently in except by switching to the tab I want or looking at the title of each tab and matching the running process with which process I think I'm running (e.g. if the tab says nano and /tmp and I'm using nano to edit a file in /tmp I'm on that tab.)

**Comment by EMH-Mark-I** [comment]
What distribution are you on? The current active tab should be slightly larger than the inactive tab.

**Comment by bmintz** [comment]
Xubuntu 17.10. Maybe they are slightly bigger, but I can't tell.

**Comment by EMH-Mark-I** [comment]
Can you share a screenshot?

**Comment by bmintz** [comment]
![screenshot of xfce4-terminal showing that the tabs do not indicate which one is selected](https://user-images.githubusercontent.com/538336/35664548-2715f202-06e8-11e8-8eb8-c542488937a8.png)

**Comment by EMH-Mark-I** [comment]
Thanks!

I have a new patch for the theme that I'll be uploading soon. It should fix this along with a laundry list of other annoyances, but I'll take a closer look to make sure the tabs are working fine. I'll probably upload it this weekend. It also looks like the scroll box arrows are missing, unless you disabled those.

**Comment by bmintz** [comment]
Good catch! I did not.

**Comment by EMH-Mark-I** [comment]
I've just uploaded the new patch. Give it a try and see if that resolves the issue; or causes more.

**Comment by bmintz** [comment]
That almost resolves the issue. It could stand to be a little clearer though. Like perhaps by making the underline for inactive tabs a little fatter.

**Comment by EMH-Mark-I** [comment]
OK I expanded the border beneath the tabs to 4px so there's more of of a gap. I also applied it for left, bottom, and right tabs as well.

**Comment by EMH-Mark-I** [comment]
So how is it now? I'm going to close the issue soon :)

**Comment by bmintz** [comment]
Yep it's fine now. Thanks!
