### ISSUE TITLE
Installation over Ubuntu/xubuntu 22.04.03 broken?

### ISSUE THREAD

**Issue by Req** [grassmunk/Chicago95#309]
I have an Ubuntu 22.04.03 system over which I did `apt install xubuntu-desktop` and logged into a xubuntu session.

I'm trying to follow https://software.opensuse.org//download.html?project=home%3Abgstack15%3AChicago95&package=chicago95-theme-all that instructs the following steps

> echo 'deb http://download.opensuse.org/repositories/home:/bgstack15:/Chicago95/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:bgstack15:Chicago95.list
> curl -fsSL https://download.opensuse.org/repositories/home:bgstack15:Chicago95/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_bgstack15_Chicago95.gpg > /dev/null
> sudo apt update
> sudo apt install chicago95-theme-all

During `apt update` I get a GPG error;

> W: GPG error: http://download.opensuse.org/repositories/home:/bgstack15:/Chicago95/xUbuntu_22.04  InRelease: The following signatures were invalid: EXPKEYSIG FB2572B7B977DBCD home:bgstack15 OBS Project <home:bgstack15@build.opensuse.org>
> E: The repository 'http://download.opensuse.org/repositories/home:/bgstack15:/Chicago95/xUbuntu_22.04  InRelease' is not signed.

Is the gpg file incorrect? Should I do something extra?

**Comment by 266-750Balloons** [comment]
You're using [this fork](https://github.com/bgstack15/Chicago95) of Chicago95, not this main repo. Ubuntu 22.04 is not supported by this project and you should probably use the Python script.

**Comment by Req** [comment]
Great point, closing

**Comment by glor** [comment]
Ahh. That's confusing because this repo proposes to install these packages. I just proposed updating the instructions to incorporate the advice from @266-750Balloons
