### ISSUE TITLE
Firefox, no borders

### ISSUE THREAD

**Issue by DocMAX** [grassmunk/Chicago95#31]
Any idea why in Firefox there are no borders around menus?

**Comment by EMH-Mark-I** [comment]
Some parts of the theme are a bit wonky. Firefox relies on the "menu" CSS class selector, which isn't specified in the theme. (I'm not sure why?) That's what's causing the missing menu border though. Some GTK3.22 applications rely on the "decoration" class for drawing menu borders, however Firefox, Thunderbird, and likely other applications out there won't. There are similar discrepancies with menu arrows, separators, and window borders.

 From my experience the "decoration" class selector isn't supported in non composited environments, so the moment you disable your compositor, menu borders and titlebars will disappear.

I've been spending some time working on a custom version of the theme for Xubuntu 17.10 that I'm going to try submitting here soon. It should fix a lot the GTK3 issues with context menus, client side decorations, icon scaling, and button padding effects. [I have a repo](https://github.com/EMH-Mark-I/Chicago95-Custom-XFCE4) up if you want to check in the meantime.

**Comment by DocMAX** [comment]
The custom version works. Thank you very much!

**Comment by EMH-Mark-I** [comment]
Good to know! I recently got invited as a contributor here so I'll be porting those changes from my custom version of the theme into the main project sometime this week or next week.

**Comment by EMH-Mark-I** [comment]
I've updated the main theme that includes a fix for this which should resolve the issue.
