### ISSUE TITLE
Some buttons/icons show wrong image

### ISSUE THREAD

**Issue by DarkReaper231** [grassmunk/Chicago95#315]
I am on latest Xubuntu and in some apps like Mousepad, many setting windows such as Appearance, Task manager, the minimize and maximize buttons show wrong icon.
![image](https://github.com/grassmunk/Chicago95/assets/38611351/0b9086b6-ccf7-492a-b8b4-3d0b379b1c55)
This does not happen in all apps, terminal shows correct icon, and so do many other apps like Palemoon for example
![image](https://github.com/grassmunk/Chicago95/assets/38611351/59512ef7-8ba6-4bb2-ad4a-68b9cf35c1c9)

This also happens for the audio icon in the panel
![image](https://github.com/grassmunk/Chicago95/assets/38611351/41a7bf09-ccd6-439c-9a60-4cdd255fda2f)

I have no idea what is causing this
I don't know if it is related but I installed pretty much everything system-wide aka `/usr/share/...`

**Comment by Dejweed** [comment]
This is probably related to the icon theme cache. Last month I changed some icons but forgot to update the cache. Try running **gtk-update-icon-cache -f _/your/icon/path/Chicago95_** ( or `gtk-update-icon-cache -f .` if you are in the icon theme's directory).

**Comment by DarkReaper231** [comment]
Oh yeah that fixed the issue! Thanks!
