### ISSUE TITLE
Animated spinner in Thunar doesn't look right (and a proposed fix)

### ISSUE THREAD

**Issue by 1chan-level-journalist** [grassmunk/Chicago95#321]
There is an option to enable a Windows Explorer-style spinner in Thunar. But here's what it currently looks like when it's active:
![orig](https://github.com/grassmunk/Chicago95/assets/16210758/2048500d-2abc-4338-b938-66739c3e3090)
That doesn't look right. So I came up with a fix (for the Windows logo version of it at least):
[throbber.zip](https://github.com/grassmunk/Chicago95/files/13853229/throbber.zip)
1. Download and unpack the archive into the "gtk-3.0" directory of Chicago95 theme,
2. Add the following line to the "thunar.css" file:
`@import url("thunar-throbber.css");`

And that should do it.
Here's what it should look like now:
![new](https://github.com/grassmunk/Chicago95/assets/16210758/f27656e9-cd0f-4536-a34b-f77021802e44)

**Comment by grassmunk** [comment]
This looks great! Would you mind sending in a pull request?

**Comment by 1chan-level-journalist** [comment]
> This looks great! Would you mind sending in a pull request?
Done.
Granted, it still doesn't look right if you decide to use any of the alternative spinners that are included in the theme. But making something universally fitting would require image editing skills that, I'm afraid, are beyond me.
