### ISSUE TITLE
Emerald Cursor I-Beam Pointer alignment incorrect

### ISSUE THREAD

**Issue by Budgiebrain994** [grassmunk/Chicago95#33]
Highlighting text using the Emerald I-beam cursor will select text against the top left-hand corner of the cursor, instead of in the middle. Selecting is fine using the other cursors.

**Comment by vitacell** [comment]
I have same problem, I love this old style cursor. "Chicago95 white" works fine.

**Comment by EMH-Mark-I** [comment]
I'm not familiar with cursors, but I'll try to take a look at it this coming weekend.

**Comment by EMH-Mark-I** [comment]
I went ahead and took a look at it anyhow. The image file for the ibeam and xterm cursors had the cursor in the incorrect position. Give it a try now and let me know if it works. (Note: Log out then log back in to your system after applying the updated cursor theme.)

**Comment by vitacell** [comment]
@EMH-Mark-I only emerald cursor has this bug, I don't know how to fix it.

**Comment by EMH-Mark-I** [comment]
@vitacell This is still happening after the patch I uploaded?

https://github.com/grassmunk/Chicago95/commit/f2f97dc88127acbdba7c92cd1ff4792f53da2eb4

You'll have to re-download the theme and copy the emerald cursor theme folder back into .icons/. Replace the older emerald cursor theme folder. Log out then log back in and try it out.

**Comment by Budgiebrain994** [comment]
@EMH-Mark-I Thanks for the fix! I'll close this issue now.
