### ISSUE TITLE
Chicago95 SDDM theme failed to load in Fedora 40

### ISSUE THREAD

**Issue by AerospaceDoe** [grassmunk/Chicago95#335]
SDDM falls back to default theme with following error message:

The current theme cannot be loaded due to the errors below, please select another theme.

file:///usr/share/sddm/themes/Chicago95/main.qml:36.1: module "QtQuick.Controls" version 1.4 is not installed

Installed Packages:
sddm-0.21.0-4.fc40.x86_64
sddm-wayland-generic-0.21.0-4.fc40.x86_64
qt5-qtquickcontrols-5.15.13-1.fc40.x86_64
qt5-qtquickcontrols2-5.15.13-1.fc40.x86_64

P.S.: SDDM default breeze theme imports "QtQuick.Controls 2.15"

A similar case is found in Fedora Forum.
https://forums.fedoraforum.org/showthread.php?332187-SDDM-login-page-shows-QtQuickControls-error

**Comment by ImgainThat** [comment]
what was the solution?? i have the same issue with a different theme that claims to be plasma 43 compatible

**Comment by AerospaceDoe** [comment]
> what was the solution?? i have the same issue with a different theme that claims to be plasma 43 compatible 

Adjust the import statements in the QML file to match the supported library versions.
Try vibe coding to debug/update the theme yourself 😄

**Comment by ImgainThat** [comment]
> > what was the solution?? i have the same issue with a different theme that claims to be plasma 43 compatible
> 
> Adjust the import statements in the QML file to match the supported library versions. Try vibe coding to debug/update the theme yourself 😄

awesome will try
