### ISSUE TITLE
[gtk-2.0] Unable to locate image file in pixmap_path: "panel/null.png"

### ISSUE THREAD

**Issue by tpenguinltg** [grassmunk/Chicago95#34]
Whenever I start a GTK2 application in a terminal, the following appears:

```
/home/pltg/.themes/Chicago95/gtk-2.0/panel.rc:366: Unable to locate image file in pixmap_path: "panel/null.png"
/home/pltg/.themes/Chicago95/gtk-2.0/panel.rc:369: Background image options specified without filename
/home/pltg/.themes/Chicago95/gtk-2.0/panel.rc:376: Unable to locate image file in pixmap_path: "panel/null.png"
/home/pltg/.themes/Chicago95/gtk-2.0/panel.rc:379: Background image options specified without filename
```

There is indeed no `null.png` in the `panel` directory. Was this meant to be `Other/null.png` like the surrounding code, or is there actually supposed to be a `panel/null.png`?

**Comment by EMH-Mark-I** [comment]
Yes, that should have pointed to the Others/ directory. I'll update that.

**Comment by EMH-Mark-I** [comment]
OK I've pushed an update that should resolve it. Check it out and let me know if everything is okay.

**Comment by tpenguinltg** [comment]
It works! No more errors. Thanks for the update.

I'll leave this open because I don't know the policy is on closing issues here, but I think this can safely be closed.

**Comment by EMH-Mark-I** [comment]
Cool!

Yeah ill just close it. Thanks for the input!
