### ISSUE TITLE
Theme color mismatching

### ISSUE THREAD

**Issue by onykage** [grassmunk/Chicago95#37]
Not sure if this is me or its a global issue, but under linux mint, xfce4, things like the software updater have a solid white background, button text also has a white background under the text.

also, on the main screen under the theme instructions, you have a list of (optional) changes to make the panel look like the screenshots, can you go into more detail there as what you mean, some of it i figured out, some of it, i didn't see the options, example, you said check 'flat buttons', on the indicator plugin, which is also a solid white bg, there is no flat buttons option there, and it makes the indicator stick out on the panel.

great project, kuddos

**Comment by EMH-Mark-I** [comment]
Thanks for the ticket!

I can take a look at the issue, but I'll need some information.
Which version of Linux Mint are you using? You should be able to check if you insert the following into a terminal.
`lsb-release -a`

Also would it be possible to see some screen shots?

For the flat buttons, I believe you are referring to step 6 (on line 64 of INSTALL.md)? _"Window Buttons (Uncheck "Show flat buttons" and "Show Handle.;" Sorting Order: None; Window grouping: Never)"_

To set that you can right click an empty area of the taskbar,  select panel in the right-click menu, then select panel preferences. 
![pic1](https://user-images.githubusercontent.com/28378002/40034914-b4aeca8a-57c4-11e8-87dc-361b0a06cbfe.png)

In panel preferences select the Items tab.
![pic2](https://user-images.githubusercontent.com/28378002/40034916-b786df2c-57c4-11e8-9127-3593345d4607.png)

In the Items tab you'll see a list of the panel plugins and items you have added. Double click on the "Window Buttons" item.
![pic3](https://user-images.githubusercontent.com/28378002/40034922-bcedadba-57c4-11e8-8f9d-f3590123f898.png)

A Window Buttons screen will come up; from there near the top are three check boxes. Of those three you'll see one for "Show flat buttons." You can un-cheack that. Essentially by un-checking that, it allows for the task items on the taskbar to have the traditional 3D toggle-button style which emphasise it as being interactive as well as provide some sense of clarity compared to flat non-styled buttons.
![pic4](https://user-images.githubusercontent.com/28378002/40034924-bec758ca-57c4-11e8-948a-bdd43d6edc0a.png)

**Comment by EMH-Mark-I** [comment]
Hey I'm just trying to catch up with you in regards to the release version of your distribution. If I can get that, I should be able to help our or test for bugs. Thanks.

**Comment by onykage** [comment]
yea, sry bout that.  been crazy past few days,  i'll get u something today

**Comment by EMH-Mark-I** [comment]
I hope that you were able to work this out?

**Comment by onykage** [comment]
nah, not yet.  Im recently unemployed and havnt had a chance to pick this
project back up.  Im praying things change soon and i can get back to my
various projects.  You will hear back from me with probably more research
then you want when i get back on my feet again ;)

-m

**Comment by EMH-Mark-I** [comment]
Oh OK, sorry to hear about that. 

Before you spend your time researching into it, I was just going to let you know that the theme currently runs on XFCE with GTK2 and GTK3.22. Ubuntu 18.04 runs GTK3.22, so everything should line up there. 

However if you're attempting to run the theme on a system running GTK3.18.9 or Ubuntu 16.04, this theme won't work.[ I made a fork of the theme for support targeting 16.04 / GTK3.18.9 users here.](https://github.com/EMH-Mark-I/Chicago95-Custom-XUbuntu-16.04-).

Good luck!
