### ISSUE TITLE
Whisker Menu Icon being resized too small

### ISSUE THREAD

**Issue by DonutDeflector** [grassmunk/Chicago95#4]
It seems like the Whisker Menu Icon is being resized drastically for whatever reasons. It seems like other GTK themes don't have the same issue.

![0025](https://cloud.githubusercontent.com/assets/15660380/19667755/b958d0c0-9a20-11e6-8fa2-d2181e53b5f1.png)
![0026](https://cloud.githubusercontent.com/assets/15660380/19667756/b95977d2-9a20-11e6-84e2-656089acc647.png)

**Comment by drazilraw** [comment]
Sorry, this isn't really relevant to your question, but would you mind sharing the icon you're using for your whisker menu? I've been looking for something like that.

Thanks!

**Comment by DonutDeflector** [comment]
Here's the link to the image: https://cdn0.vox-cdn.com/thumbor/0csUNOsUAMfelAMe6KEFaSRB8zs=/cdn0.vox-cdn.com/uploads/chorus_asset/file/6028879/win95s.0.gif

**Comment by grassmunk** [comment]
Thanks for sharing the icon. I've updated the readme. See the section labelled **Where’s the classic Start Button?** in the readme.

**Comment by DonutDeflector** [comment]
Thanks!
