### ISSUE TITLE
It doesn't crash

### ISSUE THREAD

**Issue by apiraino** [grassmunk/Chicago95#43]
### What I tried

- plug a USB peripheral
- send a forged ICMP packet to port 139

### Actual behaviour

Computer dind't crash

### Expected behaviour

![xscreensaver_simulating_windows_9x_bsod](https://user-images.githubusercontent.com/6098822/47302321-7e896b00-d621-11e8-8ab6-5181db06310b.jpg)

_(seriously, nice job)_

**Comment by grassmunk** [comment]
Optionally add a new shutdown screen?

**Comment by grassmunk** [comment]
Install xscreensaver and select the theme `BSOD`:

```
BSOD stands for "Blue Screen of Death". The finest in personal computer emulation, BSOD simulates popular screen savers from a number of less robust operating systems.
```

Example Video: https://youtu.be/YIqbMCfR3r0
