### ISSUE TITLE
Request: Permission to Redistribute

### ISSUE THREAD

**Issue by DonaldKBrown** [grassmunk/Chicago95#45]
I'm running a project called the Ninternet (https://ninternet.noreallyitis.me for reference). I would love to install this into a new image under OEM mode and redistribute this as a sort of Ninternet OS.

**Comment by EMH-Mark-I** [comment]
Well the theme is licensed GPL-3.0+/MIT so maybe? @grassmunk would might be better to answer? Just so you know, I don't know how litigious Microsoft would be over the Windows 95 startup sound, fonts, or their Icon theme being included or what license those might fall under today.

**Comment by EMH-Mark-I** [comment]
I wanted to make an update to my previous comment. Microsoft's licensed fonts are not included with this theme. I was mistaking the DOS VGA font for one.

**Comment by grassmunk** [comment]
The original link is dead, feel free to use this theme following GPL.
