### ISSUE TITLE
Gtk Warnings about deprecated Things

### ISSUE THREAD

**Issue by legacy-vault** [grassmunk/Chicago95#48]
When I launch Mousepad, it writes following Warnings to the Console:

---

(mousepad:3139): Gtk-WARNING **: 11:53:17.939: Theme parsing error: gtk.css:55:17: Not using units is deprecated. Assuming 'px'.

(mousepad:3139): Gtk-WARNING **: 11:53:17.947: Theme parsing error: gtk-widgets.css:1214:18: Not using units is deprecated. Assuming 'px'.

(mousepad:3139): Gtk-WARNING **: 11:53:18.389: Theme parsing error: <data>:2:29: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(mousepad:3139): Gtk-WARNING **: 11:53:18.389: Theme parsing error: <data>:3:37: The style property GtkButton:default-outside-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(mousepad:3139): Gtk-WARNING **: 11:53:18.389: Theme parsing error: <data>:4:27: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(mousepad:3139): Gtk-WARNING **: 11:53:18.389: Theme parsing error: <data>:5:31: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(mousepad:3139): Gtk-WARNING **: 11:53:18.389: Theme parsing error: <data>:6:28: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

---

**Comment by EMH-Mark-I** [comment]
Oh yeah, some of these are fixable. The warnings about "deprecated and shouldn't be used anymore" not so much. There are probably a number of goof ups though where a missing bracket or semi-colon need to go... I'll try fixing those at least.

**Comment by EMH-Mark-I** [comment]
OK so I have most of these knocked out. The only ones that I'm unable to fix, (and should be the case on any theme) are the warnings of deprecated style properties. These are coming from the applications themselves utilizing properties of GTK that are of course considered "deprecated." It will be the maintainers of those applications responsibility to patch.

I'll be committing my changes soon.
