### ISSUE TITLE
Buttons missing on thunar

### ISSUE THREAD

**Issue by waldganger** [grassmunk/Chicago95#57]
Hi
I am really enjoying this classic theme on my Void distribution. Only I have a problem with xfce/thunar that does'nt show the theme buttons for 
- home directory
- parent directory
- go back arrow
- go forward arrow.

I can still see Adwaita on my neofetch ouput.
Theme: Chicago95 [GTK2], Adwaita [GTK3]
Icons: Chicago95 [GTK2], Adwaita [GTK3]

Do you if it is related ?
Many thanks

**Comment by EMH-Mark-I** [comment]
Can you upload a screen capture?

Also, it might help if I know the version of void. I haven't used that distribution before.

The Chicago95 theme covers both GTK and GTK3 themes, albeit the GTK3 side might not work correctly depending on the version of GTK3 your distribution supports.

**Comment by waldganger** [comment]
Thanks for your answer.

Since my first post, I uninstalled gnome-themes-standard to get rid of adwaita stock buttons (they were black and very simple shaped) and the left and right Chicago95 arrows are here now. However, home directory and parent directory are now completely left blank. 

Here is a screen capture :

![2019-03-23-160548_790x838_scrot](https://user-images.githubusercontent.com/39879951/54867911-6eb7b380-4d86-11e9-8b07-a1f4754ec600.png)

My void distro is up to date with :
- Kernel: 4.19.30_1
- xfce4-4.12.0_7

![2019-03-23-161759_658x338_scrot](https://user-images.githubusercontent.com/39879951/54867966-7e83c780-4d87-11e9-9b70-9c3559db86fa.png)


Here is an output of gtk related installed packages :
gtk+-2.24.32_2                        GTK+ toolkit (v2)
gtk+3-3.24.7_1                        GTK+ toolkit (v3)
gtk-update-icon-cache-2.24.32_2       GTK+ toolkit (v2) - The GTK+ update icon cache tool
gtk-xfce-engine-3.2.0_2               Xfce GTK+2 theme engine
gtksourceview-3.24.10_1               Text widget that extends GTK+3 GtkTextView widget
libnm-gtk-1.8.20_2                    NetworkManager panel applet for GNOME - runtime library
webkit2gtk-2.24.0_1                   GTK+3 port of the WebKit2 browser engine
xdg-user-dirs-gtk-0.10_3              GTK+ tool to help manage user directories

**Comment by waldganger** [comment]
When I reinstall gnome-theme-standard, navigation buttons override Chicago 95 again. Strange.

![2019-03-23-191551_1600x900_scrot](https://user-images.githubusercontent.com/39879951/54869974-8e5bd580-4da0-11e9-9c2a-e21ebbecaa2a.png)

**Comment by EMH-Mark-I** [comment]
This will be caused by the version of the GTK3 toolkit installed.

The Chicago95 theme as of now is targeted for the long term stable version of GTK3, that being GTK3.22. This won't work out well for rolling release based distributions like Void, Arch, or Manjaro which are continually running newer versions of packages that require a newer version of the GTK3 toolkit; in your case that being GTK3.24.7.

It might be easier to keep up with the various released versions of the toolkit if we had the manpower; but currently that isn't the case so that's why GTK3.22 is preferred.

Let me know if you have any more questions, and thanks for submitting the issue!

**Comment by waldganger** [comment]
OK I understand, that's the downside of rolling releases. Anyway, thanks for the answer and the good work on this project.

**Comment by EMH-Mark-I** [comment]
I'm making a port of the theme for GTK3.24. I believe this will work for you once I upload it. I'm still doing some testing first. I'll upload it later this week.

**Comment by EMH-Mark-I** [comment]
Give it a try now.
