### ISSUE TITLE
[Lightdm-Webkit] Mouse cursor changing after login

### ISSUE THREAD

**Issue by bubbadoobop** [grassmunk/Chicago95#6]
This theme has been nice, but it's been annoying to have to change my mouse theme every time I log in. After I installed Lightdm-Webkit, the mouse just changes themes without any sort of input (incase you didn't know, I am using the Chicago95_Cursor_White theme for my XCursor).

**Comment by grassmunk** [comment]
This looks to be a bug with lightdm webkit setting the mouse. Does this issue happen with any other lightdm-webkit themes or just the one included here?
