### ISSUE TITLE
Shell scripts do not use batch file icons

### ISSUE THREAD

**Issue by debounce2** [grassmunk/Chicago95#60]
Shell script .sh files use the Windows 95 .sys file icon instead of the icon for .bat batch files.

**Comment by grassmunk** [comment]
Could you post a screenshot of what you're seeing?

**Comment by debounce2** [comment]
Shell script icon in theme:
![text-x-script](https://user-images.githubusercontent.com/41887007/55568990-0dd29880-5701-11e9-93b5-383621480eb1.png)

Batch file icon in Windows 95:
![batch](https://user-images.githubusercontent.com/41887007/55569041-1f1ba500-5701-11e9-90a6-ae4c7e9257ab.png)

**Comment by NullNoname** [comment]
You're probably using Thunar File Manager with the default icon size (48), but Chicago95 theme is not designed for that.
You'll need to use the "Zoom Out" command once (Ctrl+-) to change the icon size to 32. This will change the Shell Script icon to the Windows Scripting Host icon.

To change the shell scripts to use the Batch Script icon, delete the existing "Chicago95/mimes/32/application-x-shellscript.png" (which is a simlink to text-x-script.png)
and copy the batch script icon from "Chicago95/apps/32/application-default-icon.png".

If you have the Chicago95 icons installed in the ~/.icons/, the following commands will do the trick:

`rm ~/.icons/Chicago95/mimes/32/application-x-shellscript.png`
`cp ~/.icons/Chicago95/apps/32/application-default-icon.png ~/.icons/Chicago95/mimes/32/application-x-shellscript.png
`
