### ISSUE TITLE
Packaging issue with /icons/Chicago95-tux/apps/48/Verknüpfung mit simple-scan.png

### ISSUE THREAD

**Issue by FredBezies** [grassmunk/Chicago95#61]
Hello.

When I packaged your icons set, I got an error related to /icons/Chicago95-tux/apps/48/Verknüpfung mit simple-scan.png

``
Can't translate pathname 'usr/share/icons/Chicago95-tux/apps/48/Verknüpfung mit simple-scan.png' to UTF-8: Can't translate pathname 'usr/share/icons/Chicago95/apps/48/Verknüpfung mit simple-scan.png' to UTF-8
``

I think it will break icon-cache creation.

Replacing ü by a simple u in Verknüpfung can help.

**Comment by debounce2** [comment]
Changing it to a simple u did not fix it for me. I had to delete that file and now I can build icon cache without any problems.
