### ISSUE TITLE
GTK progress bar does not work

### ISSUE THREAD

**Issue by debounce2** [grassmunk/Chicago95#64]
Progress bar is invisible in transmission-gtk
![Screenshot](https://user-images.githubusercontent.com/41887007/55757961-a8aada00-5a55-11e9-85da-65e73496b85c.png)

**Comment by EMH-Mark-I** [comment]
I'll look at this. What distribution / version are you on? I'm working on a GTK3.24 port of the theme, so I suspect this might be the cause.

**Comment by debounce2** [comment]
Xubuntu 18.04 LTS. This is the only broken progress bar I have noticed so far.

**Comment by EMH-Mark-I** [comment]
OK I have a patch for this. I'll include it in my upcoming submit soon.

**Comment by EMH-Mark-I** [comment]
Give it a try now. You'll have to re-install the theme.

**Comment by debounce2** [comment]
Thanks, it works now
