### ISSUE TITLE
Firefox shows Netscape icon

### ISSUE THREAD

**Issue by chrislovins** [grassmunk/Chicago95#65]
The Firefox icon is the Netscape Navigator icon, and no matter what setting I change, be it in Menulibre, or the launcher itself, I cannot get Firefox to use the Firefox logo. I even tried deleting the Netscape Firefox icons from the theme folder and it does me no good.

**Comment by debounce2** [comment]
If you want to use the default modern Firefox icon, simply remove the Netscape version:
```
rm ~/.icons/Chicago95/apps/16/firefox.png
rm ~/.icons/Chicago95/apps/22/firefox.png
rm ~/.icons/Chicago95/apps/24/firefox.png
rm ~/.icons/Chicago95/apps/32/firefox.png
rm ~/.icons/Chicago95/apps/48/firefox.png
rm ~/.icons/Chicago95/apps/scalable/firefox.svg
```
Try switching to another icon set in Appearance Settings and then back to reload it.

**Comment by chrislovins** [comment]
I tried that, even tried switching between themes, but whenever I use your
theme, no matter if I've deleted the Firefox icons it still stays the same.

**Comment by debounce2** [comment]
It's not my theme, I'm just a user. I was able to do it that way without any issues. Check that you are modifying the correct folder that you are using. The theme and icon set are independent. Make sure you're selecting the right icon set in the Icons tab on Appearance.

**Comment by chrislovins** [comment]
Ahh sorry, the email didn't tell me who was responding, I figured it was
the developer. But yeah, I'm modifying the icons theme in my
/usr/share/icons folder, and that's the only place I have it.

**Comment by debounce2** [comment]
I would double check you deleted all 6 files. It works for me.
![Screenshot_2019-04-15_15-09-44](https://user-images.githubusercontent.com/41887007/56135393-ef865b80-5f90-11e9-972a-13942545b308.png)

**Comment by debounce2** [comment]
You can also try deleting or updating your `icon-theme.cache` file but by default, you shouldn't have one due to issue https://github.com/grassmunk/Chicago95/issues/61

**Comment by grassmunk** [comment]
Was this resolved?
