### ISSUE TITLE
[lightdm-webkit] Error caused by non-existing element

### ISSUE THREAD

**Issue by Tabascl** [grassmunk/Chicago95#66]
OS: Manjaro 18.04
XFCE: 4.13
Greeter: lightdm-webkit2-greeter

### What's happening:
An error is displayed that says that an error in the theme could interfere with the login process.
It is caused in the main.js file, in the initializeActions method.
The document.getElementById('actions-inner') call returns null, as no element has the id 'actions-inner'.

On a sidenote, the login screen seems to be messed up in a couple of ways, where some things like the buttons or text fields are not styled as they probably should be, at least on my setup.

**Comment by grassmunk** [comment]
Honestly, this uses the webkit lightdm plugin which isn't well documented and i struggled with creating. I created the SDDM theme to replace this.

**Comment by phil294** [comment]
@grassmunk how is SDDM a replacement for lightdm, the de-facto for XFCE?

I will try to fix & submit the webkit theme later - got the same error like Tabascl.

**Comment by grassmunk** [comment]
Ultimately I'm not well versed in the webkit lightdm nor am i very (or any good) at css/html5 as can be plainly seen in the super low quality of this greeter when i initially created it. I would really love for it to be upgraded and fixed to match the Win95 network logon more closely but i just lack the skillset and time to tackle it, i'm hoping someone better at it than me can help improve it. 

As for SDDM, you can easily replace lightdm with it but I can appreciate not wanting to. I feel that the SDDM greeter more closely resembles the actual win95 logon in both appearance and spirit (i.e. it adds a drop down for window manager).

**Comment by newbie029** [comment]
@grassmunk can I have the chicago95 sddm theme please?
