### ISSUE TITLE
Incorrect color fill and borders inside windows on MATE.

### ISSUE THREAD

**Issue by mknepper** [grassmunk/Chicago95#75]
I don't really know what to call this, so I'm assuming is something to do with how GTK fills things based on the .css files or whatever. 

![Screenshot at 2019-07-06 18-17-57](https://user-images.githubusercontent.com/12740958/60762003-eac6c600-a01a-11e9-94b1-a71ec7506e25.png)

OS: Xubuntu 18.04 LTS
DE: MATE (package: mate-desktop-environment)

**Comment by EMH-Mark-I** [comment]
I'm looking over this now.

**Comment by EMH-Mark-I** [comment]
I opened a [branch for mate-desktop](https://github.com/grassmunk/Chicago95/tree/mate-desktop) that you can test out. I made some changes to the control centre as well as caja.

**Comment by EMH-Mark-I** [comment]
With these changes now merged into the main branch, I'm going to close the branch that I opened for for mate desktops. See commits e630507 and 831c2d5.
