### ISSUE TITLE
Redo SVG Icons

### ISSUE THREAD

**Issue by grassmunk** [grassmunk/Chicago95#78]
One known issues is that SVG icons have weird issues at certain sizes. To fix that the icons need to be redone using: https://github.com/cyChop/pixel2svg-fork

This pixel2svg fork adds alpha transparency. In playing around with the tool i've noticed there's a flag to overlap pixels: `--overlap` also the default "square size" is 40, experimenting while working on the KDE theme its looks like pixel size 2 is best. 

I'd like to go back and redo all the SVG icons with the following: ` pixel2svg --squaresize=2 --overlap icon.png`

**Comment by vitacell** [comment]
![Captura de pantalla_2019-07-31_20-41-09](https://user-images.githubusercontent.com/18006295/62238942-3da25c00-b3d4-11e9-81d0-fafd94d73038.png)
![Captura de pantalla_2019-07-31_20-43-17](https://user-images.githubusercontent.com/18006295/62238950-42671000-b3d4-11e9-9aea-d6a14dbf1c4a.png)
![Captura de pantalla_2019-07-31_20-45-24](https://user-images.githubusercontent.com/18006295/62239109-8eb25000-b3d4-11e9-846d-566a8cf263d1.png)
![Captura de pantalla_2019-07-31_20-45-55](https://user-images.githubusercontent.com/18006295/62239113-907c1380-b3d4-11e9-9c1c-e6d81c45865d.png)

**Comment by grassmunk** [comment]
This is because there's set icons for size 48/32/16 but above that it uses the SVG, which has this known problem.

**Comment by grassmunk** [comment]
I've created a new python tool to try and fix these using inkscape:

```python
#!/usr/bin/env python

# Tool to fix transarencies in pixel2svg icons
# GPL 3.0
# Copyright Grassmunk


import xml.etree.ElementTree as ET
import re
import sys
import os

''' File to fix pixel icons for Chicago95 '''
tmp_file = "./chicago95_tmp_file.svg"
print "[+] Creating tmp file", tmp_file
cmd = "inkscape -l "+ tmp_file +" "+sys.argv[1]
print "[!] Executing command:", cmd
os.system(cmd)
print "[+] Parsing", tmp_file
SVG_NS = "http://www.w3.org/2000/svg"
svg = ET.parse(tmp_file)
rects = svg.findall('.//{%s}rect' % SVG_NS)
rgbs = {}
print '[+] Getting colors and ids'
for rect in rects:
    rect_id = rect.attrib['id']
    rgb = rect.attrib['fill']
    if rgb not in rgbs:
        rgbs[rgb] = rect_id
for rgb in rgbs:
    print '\t[id]', rgbs[rgb], rgb
print "[+] Joining same colors\n[!] Inkscape will open and close here a few times"
for rgb in rgbs:
    print '[+] Working on', rgbs[rgb], rgb
    cmd = "inkscape --select=" + rgbs[rgb] +" --verb EditSelectSameFillColor --verb SelectionCombine --verb SelectionUnion --verb FileSave --verb FileQuit "+ tmp_file
    os.system(cmd)
print '[+] Moving tmp file', tmp_file, 'to original file', sys.argv[1]
cmd = 'mv '+tmp_file+' '+sys.argv[1]
print "[!] Executing command:", cmd
os.system(cmd)
print '[+] Done!'
```

Output:
```
[+] Creating tmp file ./chicago95_tmp_file.svg
[!] Executing command: inkscape -l ./chicago95_tmp_file.svg terminal.svg
[+] Parsing ./chicago95_tmp_file.svg
[+] Getting colors and ids
	[id] rect4 rgb(0,0,0)
	[id] rect42 rgb(255,255,255)
	[id] rect126 rgb(255,255,0)
	[id] rect82 rgb(192,192,192)
	[id] rect712 rgb(255,0,0)
[+] Joining same colors
[!] Inkscape will open and close here a few times
[+] Working on rect4 rgb(0,0,0)
[+] Working on rect42 rgb(255,255,255)
[+] Working on rect126 rgb(255,255,0)
[+] Working on rect82 rgb(192,192,192)
[+] Working on rect712 rgb(255,0,0)
[+] Moving tmp file ./chicago95_tmp_file.svg to original file terminal.svg
[!] Executing command: mv ./chicago95_tmp_file.svg terminal.svg
[+] Done!
```

**Comment by grassmunk** [comment]
Using the tool above here's a before and after of old vs new:
![image](https://user-images.githubusercontent.com/3452173/66292409-174be180-e899-11e9-9375-5923361a3795.png)
![image](https://user-images.githubusercontent.com/3452173/66292424-22067680-e899-11e9-833e-0e544d19118c.png)

Since i replaced a bunch of stuff i'm going to create a branch for people to test out

**Comment by grassmunk** [comment]
@EMH-Mark-I and @vitacell please test https://github.com/grassmunk/Chicago95/tree/scaled_icons which should fix this issue

**Comment by grassmunk** [comment]
Looks like no one tested this, i've merged in to master

**Comment by EMH-Mark-I** [comment]
I don't recall seeing an email to test the icons; else I would have.
