### ISSUE TITLE
Having troubles with PulseAudio mixer-icon

### ISSUE THREAD

**Issue by vitacell** [grassmunk/Chicago95#83]
![Captura de pantalla_2019-07-30_15-45-25](https://user-images.githubusercontent.com/18006295/62135133-fb98ed80-b2e1-11e9-85cd-1bada6ebe519.png)
![Captura de pantalla_2019-07-30_15-46-23](https://user-images.githubusercontent.com/18006295/62135137-fd62b100-b2e1-11e9-85d5-8838cbe25366.png)

Hi, Tryed everything, resizing panel, adjusting icons in gtkrc, panel. And I never can PulseAudio's icon match in size with other icons on the panel (launcher icons, notification icons).

Also when I press PulseAudio's icon, it's menu looks broken (volume level slider adjustement, and his background)(see the image). This doesn't happen with other themes.

No, I don't have .gtkrc-2.0 in my home dir.

**Comment by EMH-Mark-I** [comment]
This issue was resolved in issue #84
