### ISSUE TITLE
Are any donations needed to keep these projects running?

### ISSUE THREAD

**Issue by DougBeney** [grassmunk/Chicago95#89]
I love your work and your themes are very well documented. Wouldn't mind passing on a few dollars as a thank you. Have you thought of setting up a BeerPay or something like it? Thanks.

**Comment by EMH-Mark-I** [comment]
I don't believe donations are needed, but I will leave that up to @grassmunk .

**Comment by grassmunk** [comment]
If we did accept donations they'd mostly have to go to @EMH-Mark-I for all the amazing work he's doing. 

My concern is the second we start taking money i fear MS and some of the other icons we're using may come after us.

**Comment by DougBeney** [comment]
Didn't even think of that. Thanks for addressing.
