### ISSUE TITLE
Desktop icons are not tinted when selected

### ISSUE THREAD

**Issue by okanarbik** [grassmunk/Chicago95#98]
Not sure if I misconfigured something but IIRC desktop icons are supposed to be tinted when selected. The issue seems to be in XfdesktopIconView.view in .themes/Chicago95/gtk-3.24/apps/xfce.css
Is this intentional?

I've changed xfce.css locally to achieve a similar effect (and also made selection box transparent)
```
XfdesktopIconView.view {
  background: @xfd_icon_backdrop;
  border-radius: 0px; }
  XfdesktopIconView.view:active {
    background: @selected_bg_color;
    color: @selected_bg_color;
    text-shadow: none; }
  XfdesktopIconView.view .label {
    text-shadow: none;
    color: @font_bright; }
  XfdesktopIconView.view .rubberband {
    border: 1px dotted #ccc;
    background: transparent; }
```

**Comment by okanarbik** [comment]
Screenshot of the css snippet. Selection box change produces artifacts
![Screenshot_2019-10-02_15-02-14](https://user-images.githubusercontent.com/33345742/66042649-b2555c00-e525-11e9-8898-7dc0bbfe8cbd.png)

**Comment by EMH-Mark-I** [comment]
I'll check it out,
