### ISSUE TITLE
Cannot get chicago95 to show up as a global theme

### ISSUE THREAD

**Issue by verbose1** [grassmunk/Chicago95#99]
I have followed the installation instructions of how to install it and when I go to global theme or plasma style on manjaro the theme is not there. icons show up, window manager shows up, but not global themes.

**Comment by verbose1** [comment]
ok i solved the issue by switching my DE, but it should be noted that chicago95 did not work with plasma.

**Comment by grassmunk** [comment]
In the README (
https://github.com/grassmunk/Chicago95#requirements) its states:

```
Requirements
GTK+ 3.22 or 3.24
Xfce 4.12 or 4.14
```

We are currently working on a plasma variant, thank you for the feedback.
